### ISSUE TITLE
Infinispan is not getting installed while installing Karavan on Kubernetes

### ISSUE THREAD

**Issue by hushen-savani-azilen** [apache/camel-karavan#1023]
Karavan installation on Kubetnets is buggy. The wizard says Karavan is installed successfully, but in real it's not. The UI is stuck at this stage,

![image](https://github.com/apache/camel-karavan/assets/101381710/e8ddbd40-b16f-4da7-a25c-692b2fcee8a0)

The reason is Infinispan is not getting installed while installing Karavan on Kubernetes.

![image](https://github.com/apache/camel-karavan/assets/101381710/f62e7ab7-e48f-4083-9d56-33344113133b)

Kindly fix this issue ASAP.

And how to seperately install Infinispan for Karavan if it fails?

**Comment by hushen-savani-azilen** [comment]
I'm following this guide for Karavan installation by the way,

https://github.com/apache/camel-karavan/blob/main/docs/WEB_KUBERNETES.md

**Comment by RafiIsaharov** [comment]
I have the same issue, but when using wed_docker.md:

`2023-12-10 15:04:30,921 INFO  [org.inf.HOTROD] (executor-thread-2) ISPN004074: Native Epoll transport not available, using NIO instead: io.netty.channel.epoll.Epoll
2023-12-10 15:04:30,921 INFO  [org.inf.HOTROD] (executor-thread-2) ISPN004108: Native IOUring transport not available, using NIO instead: io.netty.incubator.channel.uring.IOUring
2023-12-10 15:04:31,034 INFO  [org.inf.HOTROD] (executor-thread-2) ISPN004021: Infinispan version: Infinispan 'Flying Saucer' 14.0.17.Final
2023-12-10 15:04:33,015 INFO  [org.apa.cam.kar.inf.InfinispanService] (executor-thread-2) InfinispanService is starting in remote mode
2023-12-10 15:04:33,059 INFO  [org.inf.HOTROD] (executor-thread-2) ISPN004021: Infinispan version: Infinispan 'Flying Saucer' 14.0.17.Final
...
...
2023-12-10 15:07:30,925 ERROR [io.qua.ver.cor.run.VertxCoreRecorder] (vert.x-eventloop-thread-2) Uncaught exception received by Vert.x: java.lang.RuntimeException: java.lang.Exception: Not connected...
        at io.quarkus.vertx.runtime.VertxEventBusConsumerRecorder.wrapIfNecessary(VertxEventBusConsumerRecorder.java:207)
        at io.quarkus.vertx.runtime.VertxEventBusConsumerRecorder$3$1$2.handle(VertxEventBusConsumerRecorder.java:146)
        at io.quarkus.vertx.runtime.VertxEventBusConsumerRecorder$3$1$2.handle(VertxEventBusConsumerRecorder.java:138)
        at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:180)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:277)
        at io.vertx.core.impl.ContextBase.lambda$internalExecuteBlocking$2(ContextBase.java:199)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1512)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.Exception: Not connected...
        at org.apache.camel.karavan.infinispan.InfinispanService.start(InfinispanService.java:119)
        at org.apache.camel.karavan.infinispan.InfinispanService.tryStart(InfinispanService.java:80)
        at org.apache.camel.karavan.infinispan.InfinispanService_Subclass.tryStart$$superforward(Unknown Source)
        at org.apache.camel.karavan.infinispan.InfinispanService_Subclass$$function$$1.apply(Unknown Source)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
        at io.smallrye.faulttolerance.FaultToleranceInterceptor.lambda$syncFlow$3(FaultToleranceInterceptor.java:253)
        at io.smallrye.faulttolerance.core.InvocationContext.call(InvocationContext.java:20)
        at io.smallrye.faulttolerance.core.Invocation.apply(Invocation.java:29)
        at io.smallrye.faulttolerance.core.retry.Retry.doApply(Retry.java:88)
        at io.smallrye.faulttolerance.core.retry.Retry.apply(Retry.java:42)
        at io.smallrye.faulttolerance.FaultToleranceInterceptor.syncFlow(FaultToleranceInterceptor.java:255)
        at io.smallrye.faulttolerance.FaultToleranceInterceptor.intercept(FaultToleranceInterceptor.java:182)
        at io.smallrye.faulttolerance.FaultToleranceInterceptor_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
        at org.apache.camel.karavan.infinispan.InfinispanService_Subclass.tryStart(Unknown Source)
        at org.apache.camel.karavan.service.KaravanService.startServices(KaravanService.java:134)
        at org.apache.camel.karavan.service.KaravanService_VertxInvoker_startServices_094be2f3e48c5e3b3465ddbb4f32b0fa4835c9c6.invokeBean(Unknown Source)
        at io.quarkus.vertx.runtime.EventConsumerInvoker.invoke(EventConsumerInvoker.java:45)
        at io.quarkus.vertx.runtime.VertxEventBusConsumerRecorder$3$1$2.handle(VertxEventBusConsumerRecorder.java:142)
        ... 11 more

`

**Comment by mgubaidullin** [comment]
Check you Kubernetes logs and events to understand why infinispan image could not be pulled from docker registry (ImagePullBackOff)

**Comment by juarinu** [comment]
The same issue following the "wed_docker.md" guide. The container starts, logs "Infinispan is started" but then enters in a loop with "InifispanService is starting in remote mode". Finally, an exception "Not connected..." and the container shuts down. I'm in a Linux server with docker 2.21.0.

**Comment by mgubaidullin** [comment]
There won't be Infinispan in the next version https://github.com/apache/camel-karavan/issues/1115
