### ISSUE TITLE
Failed to run created demo project with container \"demo\" in pod \"demo\" is waiting to start: ContainerCreating

### ISSUE THREAD

**Issue by RafiIsaharov** [apache/camel-karavan#1029]
The camel-karavan service was installed in minikube v1.32.0 with the docker driver on Ubunto 22.04 via WSL2 on Windows 10
created a simple project from YouTube example https://www.youtube.com/watch?v=3ucMUM7YfU8&ab_channel=Karavan
With timer source and message to log, run example on dev mode and failed with the message bellow:

{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"container \"demo\" in pod \"demo\" is waiting to start: ContainerCreating","reason":"BadRequest","code":400}

**Comment by mgubaidullin** [comment]
Can you check in minikube if demo container is running?

**Comment by RafiIsaharov** [comment]
> Can you check in minikube if demo container is running?
Hi [mgubaidullin](https://github.com/mgubaidullin) , minikube is also running, and the Karavan pods are running. See below :

> user:/mnt/c/WINDOWS/system32$ minikube status

minikube
type: Control Plane
host: Running
kubelet: Running
apiserver: Running
kubeconfig: Configured 

> user:/mnt/c/WINDOWS/system32$ minikube kubectl -- get pods -A

NAMESPACE              NAME                                         READY   STATUS    RESTARTS        AGE
karavan                gitea-864f5b58c5-k8ck7                       1/1     Running   1 (2d14h ago)   2d18h
karavan                infinispan-0                                 1/1     Running   1 (2d14h ago)   2d18h
karavan                karavan-5bbdc4594c-jggwx                     1/1     Running   1 (2d14h ago)   2d18h
kube-system            coredns-5dd5756b68-qmgk2                     0/1     Running   1 (2d14h ago)   2d19h
kube-system            etcd-minikube                                1/1     Running   1 (2d14h ago)   2d19h
kube-system            kube-apiserver-minikube                      1/1     Running   1 (2d14h ago)   2d19h
kube-system            kube-controller-manager-minikube             1/1     Running   1 (2d14h ago)   2d19h
kube-system            kube-proxy-tjwp8                             1/1     Running   1 (2d14h ago)   2d19h
kube-system            kube-scheduler-minikube                      1/1     Running   1 (2d14h ago)   2d19h
kube-system            metrics-server-7c66d45ddc-7pw58              0/1     Running   1 (2d14h ago)   2d18h
kube-system            registry-542q4                               1/1     Running   1 (2d14h ago)   2d19h
kube-system            registry-proxy-zhdzr                         1/1     Running   1 (2d14h ago)   2d19h
kube-system            storage-provisioner                          1/1     Running   2 (2d14h ago)   2d19h
kubernetes-dashboard   dashboard-metrics-scraper-7fd5cb4ddc-vmjdr   1/1     Running   1 (2d14h ago)   2d19h
kubernetes-dashboard   kubernetes-dashboard-8694d4445c-wlx7j        1/1     Running   1 (2d14h ago)   2d19h

**Comment by mgubaidullin** [comment]
I meant to check the `demo` container in the `demo` pod that you have started

**Comment by RafiIsaharov** [comment]
`minikube kubectl -- describe pod demo -n karavan`
Name:             demo
Namespace:        karavan
Priority:         0
Service Account:  default
Node:             minikube/192.168.49.2
Start Time:       Mon, 18 Dec 2023 02:09:56 +0200
Labels:           app.kubernetes.io/name=demo
                  app.kubernetes.io/part-of=karavan
                  app.kubernetes.io/runtime=camel
                  org.apache.camel.karavan/projectId=demo
                  org.apache.camel.karavan/type=devmode
Annotations:      <none>
Status:           Failed
IP:               10.244.0.9
IPs:
  IP:  10.244.0.9
Containers:
  demo:
    Container ID:   docker://41e2592ab7b7c12723ae1c6cd957b3df7bb51bfa26aaad0a2879af6577a60c1d
    Image:          ghcr.io/apache/camel-karavan-devmode:4.1.0
    Image ID:       docker-pullable://ghcr.io/apache/camel-karavan-devmode@sha256:85ed34ac7560e3ecbbaf70ea4ebc7ce3005e35020e480c08089096ba249cd516
    Port:           8080/TCP
    Host Port:      0/TCP
    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 18 Dec 2023 02:11:53 +0200
      Finished:     Mon, 18 Dec 2023 02:11:59 +0200
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  2Gi
    Requests:
      cpu:     500m
      memory:  256Mi
    Environment:
      JBANG_OPTIONS:
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-cmk78 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  demo:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  demo
    ReadOnly:   false
  maven-settings:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      karavan
    Optional:  false
  kube-api-access-cmk78:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age    From               Message
  ----    ------     ----   ----               -------
  Normal  Scheduled  6m56s  default-scheduler  Successfully assigned karavan/demo to minikube
  Normal  Pulling    6m56s  kubelet            Pulling image "ghcr.io/apache/camel-karavan-devmode:4.1.0"
  Normal  Pulled     5m     kubelet            Successfully pulled image "ghcr.io/apache/camel-karavan-devmode:4.1.0" in 1m56.346s (1m56.346s including waiting)
  Normal  Created    4m59s  kubelet            Created container demo
  Normal  Started    4m59s  kubelet            Started container demo

**Comment by RafiIsaharov** [comment]
` minikube kubectl -- logs demo -c demo -n karavan`

2023-12-18 00:11:54.842  INFO 15 --- [           main] org.apache.camel.main.MainSupport   : Apache Camel (JBang) 4.1.0 is starting
2023-12-18 00:11:54.999  INFO 15 --- [           main] org.apache.camel.main.MainSupport   : Using Java 17.0.8 with PID 15. Started by karavan in /karavan/code
2023-12-18 00:11:59.323 ERROR 15 --- [           main] .download.MavenDependencyDownloader : Error downloading: org.apache.camel:camel-rest:4.1.0 due to: org.apache.camel.main.download.DownloadException: Cannot resolve dependencies in https://repo1.maven.org/maven2
java.util.concurrent.ExecutionException: org.apache.camel.main.download.DownloadException: Cannot resolve dependencies in https://repo1.maven.org/maven2
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
        at java.util.concurrent.FutureTask.get(FutureTask.java:205) ~[?:?]
        at org.apache.camel.main.download.DownloadThreadPool.awaitCompletion(DownloadThreadPool.java:75) ~[camel-kamelet-main-4.1.0.jar:4.1.0]
        at org.apache.camel.main.download.DownloadThreadPool.download(DownloadThreadPool.java:67) ~[camel-kamelet-main-4.1.0.jar:4.1.0]
        at org.apache.camel.main.download.MavenDependencyDownloader.doDownloadDependency(MavenDependencyDownloader.java:222) ~[camel-kamelet-main-4.1.0.jar:4.1.0]
        at org.apache.camel.main.download.MavenDependencyDownloader.downloadDependency(MavenDependencyDownloader.java:187) ~[camel-kamelet-main-4.1.0.jar:4.1.0]
        at org.apache.camel.main.download.MavenDependencyDownloader.downloadDependency(MavenDependencyDownloader.java:172) ~[camel-kamelet-main-4.1.0.jar:4.1.0]
        at org.apache.camel.main.download.DependencyDownloaderComponentResolver.resolveComponent(DependencyDownloaderComponentResolver.java:64) ~[camel-kamelet-main-4.1.0.jar:4.1.0]
        at org.apache.camel.impl.engine.AbstractCamelContext.initComponent(AbstractCamelContext.java:613) ~[camel-base-engine-4.1.0.jar:4.1.0]
        at org.apache.camel.impl.engine.AbstractCamelContext.lambda$getComponent$1(AbstractCamelContext.java:541) ~[camel-base-engine-4.1.0.jar:4.1.0]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[?:?]
        at org.apache.camel.impl.engine.AbstractCamelContext.getComponent(AbstractCamelContext.java:539) ~[camel-base-engine-4.1.0.jar:4.1.0]
        at org.apache.camel.impl.engine.AbstractCamelContext.getComponent(AbstractCamelContext.java:514) ~[camel-base-engine-4.1.0.jar:4.1.0]
        at org.apache.camel.main.BaseMainSupport.lambda$doAutoConfigurationFromProperties$29(BaseMainSupport.java:1699) ~[camel-main-4.1.0.jar:4.1.0]
        at org.apache.camel.main.MainHelper.computeProperties(MainHelper.java:407) [camel-main-4.1.0.jar:4.1.0]
        at org.apache.camel.main.BaseMainSupport.doAutoConfigurationFromProperties(BaseMainSupport.java:1693) [camel-main-4.1.0.jar:4.1.0]
        at org.apache.camel.main.BaseMainSupport.autoConfigurationFromProperties(BaseMainSupport.java:1656) [camel-main-4.1.0.jar:4.1.0]
        at org.apache.camel.main.BaseMainSupport.autoconfigure(BaseMainSupport.java:450) [camel-main-4.1.0.jar:4.1.0]
        at org.apache.camel.main.MainSupport.autoconfigure(MainSupport.java:73) [camel-main-4.1.0.jar:4.1.0]
        at org.apache.camel.main.KameletMain.autoconfigure(KameletMain.java:600) [camel-kamelet-main-4.1.0.jar:4.1.0]
        at org.apache.camel.main.BaseMainSupport.postProcessCamelContext(BaseMainSupport.java:649) [camel-main-4.1.0.jar:4.1.0]
        at org.apache.camel.main.MainSupport.initCamelContext(MainSupport.java:339) [camel-main-4.1.0.jar:4.1.0]
        at org.apache.camel.main.KameletMain.doInit(KameletMain.java:308) [camel-kamelet-main-4.1.0.jar:4.1.0]
        at org.apache.camel.support.service.BaseService.init(BaseService.java:78) [camel-api-4.1.0.jar:4.1.0]
        at org.apache.camel.support.service.BaseService.start(BaseService.java:105) [camel-api-4.1.0.jar:4.1.0]
        at org.apache.camel.dsl.jbang.core.commands.Run.runKameletMain(Run.java:980) [camel-jbang-core-4.1.0.jar:4.1.0]
        at org.apache.camel.dsl.jbang.core.commands.Run.run(Run.java:738) [camel-jbang-core-4.1.0.jar:4.1.0]
        at org.apache.camel.dsl.jbang.core.commands.Run.doCall(Run.java:279) [camel-jbang-core-4.1.0.jar:4.1.0]
        at org.apache.camel.dsl.jbang.core.commands.CamelCommand.call(CamelCommand.java:71) [camel-jbang-core-4.1.0.jar:4.1.0]
        at org.apache.camel.dsl.jbang.core.commands.CamelCommand.call(CamelCommand.java:36) [camel-jbang-core-4.1.0.jar:4.1.0]
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041) [picocli-4.7.5.jar:4.7.5]
        at picocli.CommandLine.access$1500(CommandLine.java:148) [picocli-4.7.5.jar:4.7.5]
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461) [picocli-4.7.5.jar:4.7.5]
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453) [picocli-4.7.5.jar:4.7.5]
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415) [picocli-4.7.5.jar:4.7.5]
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273) [picocli-4.7.5.jar:4.7.5]
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417) [picocli-4.7.5.jar:4.7.5]
        at picocli.CommandLine.execute(CommandLine.java:2170) [picocli-4.7.5.jar:4.7.5]
        at org.apache.camel.dsl.jbang.core.commands.CamelJBangMain.run(CamelJBangMain.java:165) [camel-jbang-core-4.1.0.jar:4.1.0]
        at main.CamelJBang.main(CamelJBang.java:36) [CamelJBang.jar:?]
Caused by: org.apache.camel.main.download.DownloadException: Cannot resolve dependencies in https://repo1.maven.org/maven2

**Comment by RafiIsaharov** [comment]
The issue was resolved after I added DNS: nameserver 8.8.8.8 to /etc/resolv.conf and restarted coredns in the kube-system namespace of Minikube Kubernetes cluster.
commands to resolve the issue: 
`minikube ssh
sudo sh -c 'echo "nameserver 8.8.8.8" >> /etc/resolv.conf'
minikube kubectl -- rollout restart -n kube-system deployment coredns`

**Comment by RafiIsaharov** [comment]
The issue was resolved after I added DNS: nameserver 8.8.8.8 to /etc/resolv.conf and restarted coredns in the kube-system namespace of Minikube Kubernetes cluster.
commands to resolve the issue:
minikube ssh
sudo sh -c 'echo "nameserver 8.8.8.8" >> /etc/resolv.conf'
minikube kubectl -- rollout restart -n kube-system deployment coredns
