### ISSUE TITLE
error when running saga with option

### ISSUE THREAD

**Issue by huuhoait** [apache/camel-karavan#1055]
Hi ,
  I try using saga with karavan but i got an issue
Caused by: java.lang.NullPointerException: Cannot invoke "org.apache.camel.model.PropertyExpressionDefinition.getKey()" because "def" is null
        at org.apache.camel.reifier.SagaReifier.createProcessor(SagaReifier.java:56)

        at org.apache.camel.reifier.ProcessorReifier.makeProcessor(ProcessorReifier.java:870)
        at org.apache.camel.reifier.ProcessorReifier.addRoutes(ProcessorReifier.java:610)
        at org.apache.camel.reifier.RouteReifier.doCreateRoute(RouteReifier.java:213)
        ... 27 more

[Archive.zip](https://github.com/apache/camel-karavan/files/13867734/Archive.zip)

**Comment by davsclaus** [comment]
Thanks for reporting, its a bug in camel-yaml-dsl and not Karavan
