### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot find RoutesBuilderLoader in classpath supporting file extension: json

### ISSUE THREAD

**Issue by rapetum228** [apache/camel-karavan#1132]
Hello. First of all I want to thank you for such an interesting project for creating integrations. 
However, there are some difficulties. 
I get this error when reloading an integration in DEV mode in Docker:
```log
2024-02-19 21:02:38.998  WARN 16 --- [ ReloadOnDemand] support.RouteOnDemandReloadStrategy : Error reloading routes due to Cannot find RoutesBuilderLoader in classpath supporting file extension: json. This exception is ignored.
java.lang.IllegalArgumentException: Cannot find RoutesBuilderLoader in classpath supporting file extension: json
	at org.apache.camel.impl.engine.DefaultRoutesLoader.resolveRoutesBuilderLoader(DefaultRoutesLoader.java:298) ~[camel-base-engine-4.3.0.jar:4.3.0]
	at org.apache.camel.impl.engine.DefaultRoutesLoader.findRoutesBuilders(DefaultRoutesLoader.java:124) ~[camel-base-engine-4.3.0.jar:4.3.0]
	at org.apache.camel.impl.engine.DefaultRoutesLoader.findRoutesBuilders(DefaultRoutesLoader.java:101) ~[camel-base-engine-4.3.0.jar:4.3.0]
	at org.apache.camel.impl.engine.DefaultRoutesLoader.updateRoutes(DefaultRoutesLoader.java:270) ~[camel-base-engine-4.3.0.jar:4.3.0]
	at org.apache.camel.support.RouteWatcherReloadStrategy.onRouteReload(RouteWatcherReloadStrategy.java:289) ~[camel-support-4.3.0.jar:4.3.0]
	at org.apache.camel.support.RouteOnDemandReloadStrategy.doOnReload(RouteOnDemandReloadStrategy.java:114) ~[camel-support-4.3.0.jar:4.3.0]
	at org.apache.camel.support.RouteOnDemandReloadStrategy.onReload(RouteOnDemandReloadStrategy.java:74) ~[camel-support-4.3.0.jar:4.3.0]
	at org.apache.camel.impl.console.ReloadDevConsole.lambda$doCallJson$1(ReloadDevConsole.java:71) ~[camel-console-4.3.0.jar:4.3.0]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
```
I want to use JSON Schema Validator that references a json file with a schema. At initial startup after container creation everything works correctly. However, after restarting I get a warning after which all routes stop working.

**Comment by rapetum228** [comment]
Also after building the image I get an error that the file is not found
```log
java.io.FileNotFoundException: my-validator.json does not exists
	at org.apache.camel.impl.engine.DefaultResourceResolvers$FileResolver$1.getInputStream(DefaultResourceResolvers.java:76)
	at org.apache.camel.support.ResourceHelper.resolveResourceAsInputStream(ResourceHelper.java:133)
	at org.apache.camel.support.ResourceHelper.resolveMandatoryResourceAsInputStream(ResourceHelper.java:111)
	at org.apache.camel.component.jsonvalidator.DefaultJsonUriSchemaLoader.createSchema(DefaultJsonUriSchemaLoader.java:44)
	at org.apache.camel.component.jsonvalidator.JsonValidatorEndpoint.getOrCreateSchema(JsonValidatorEndpoint.java:163)
	at org.apache.camel.component.jsonvalidator.JsonValidatorEndpoint.onExchange(JsonValidatorEndpoint.java:97)
	at org.apache.camel.support.ProcessorEndpoint$1.process(ProcessorEndpoint.java:61)
	at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:65)
	at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:172)
	at org.apache.camel.impl.engine.CamelInternalProcessor.processNonTransacted(CamelInternalProcessor.java:354)
	at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:330)
	at org.apache.camel.processor.Pipeline$PipelineTask.run(Pipeline.java:102)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.doRun(DefaultReactiveExecutor.java:199)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.executeReactiveWork(DefaultReactiveExecutor.java:189)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.tryExecuteReactiveWork(DefaultReactiveExecutor.java:166)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:148)
	at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:59)
	at org.apache.camel.processor.Pipeline.process(Pipeline.java:163)
	at org.apache.camel.impl.engine.CamelInternalProcessor.processNonTransacted(CamelInternalProcessor.java:354)
	at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:330)
	at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:81)
	at org.apache.camel.support.AsyncProcessorSupport.process(AsyncProcessorSupport.java:32)
	at org.apache.camel.component.platform.http.vertx.VertxPlatformHttpConsumer.processExchange(VertxPlatformHttpConsumer.java:236)
	at org.apache.camel.component.platform.http.vertx.VertxPlatformHttpConsumer.lambda$handleRequest$1(VertxPlatformHttpConsumer.java:204)
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$0(ContextBase.java:167)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:277)
	at io.vertx.core.impl.ContextBase.lambda$internalExecuteBlocking$2(ContextBase.java:199)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by davsclaus** [comment]
Camel 4.4 has been release you can try using that version, or wait for karavan to release with 4.4 out of the box

**Comment by rapetum228** [comment]
@davsclaus updated to version 4.4.0. Problem still exists

**Comment by davsclaus** [comment]
Can you put together a sample project what you do and attach the files here or put somewhere where I can take a look

**Comment by rapetum228** [comment]
@davsclaus I attach the test repository https://github.com/rapetum228/karavan-test.
Test project files https://github.com/rapetum228/karavan-test/tree/main/test

Everything works in DEV mode. When I run it through 'Run' in web IDE

![image](https://github.com/apache/camel-karavan/assets/90648341/fd8ac355-77bb-4788-81d7-1580f89f8b57)

 Except that JsonSchemaValidator sees any string as correct when an incorrect time format is sent. For example
 ```json
 {
    "eventTime": "incirrect date-time string",
    "id": 1,
    "name": "test"
}
 ```
And when I build a finished image, using "Build"
![image](https://github.com/apache/camel-karavan/assets/90648341/49bddf10-37b5-4767-9e16-74425fdaad0e)

And run it from the registry, for example with this command 

````cmd
docker run -p 8097:8080 localhost:5555/karavan/test:dev
```

Then I get this error when sending a message:
```markdown
<a name="log-error"></a>
<details>
  <summary markdown="span">Log of error</summary>
```log
2024-04-08 14:57:10.055 ERROR 1 --- [worker-thread-0] or.errorhandler.DefaultErrorHandler : Failed delivery for (MessageId: F56780053D81F7B-0000000000000000 on ExchangeId: F56780053D81F7B-0000000000000000). Exhausted after delivery attempt: 1 caught: java.io.FileNotFoundException: my-validator.json does not exist

Message History (source location and message history is disabled)
---------------------------------------------------------------------------------------------------------------------------------------
Source                                   ID                             Processor                                          Elapsed (ms)
                                         post-2bc7/post-2bc7            from[platform-http:///test?httpMethodRestrict=POST           18

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------
java.io.FileNotFoundException: my-validator.json does not exist
        at org.apache.camel.impl.engine.DefaultResourceResolvers$FileResolver$1.getInputStream(DefaultResourceResolvers.java:76) ~[test-1.jar:?]
        at org.apache.camel.support.ResourceHelper.resolveResourceAsInputStream(ResourceHelper.java:133) ~[test-1.jar:?]        at org.apache.camel.support.ResourceHelper.resolveMandatoryResourceAsInputStream(ResourceHelper.java:111) ~[test-1.jar:?]
        at org.apache.camel.component.jsonvalidator.DefaultJsonUriSchemaLoader.createSchema(DefaultJsonUriSchemaLoader.java:44) ~[test-1.jar:?]
        at org.apache.camel.component.jsonvalidator.JsonValidatorEndpoint.getOrCreateSchema(JsonValidatorEndpoint.java:183) ~[test-1.jar:?]
        at org.apache.camel.component.jsonvalidator.JsonValidatorEndpoint.onExchange(JsonValidatorEndpoint.java:118) ~[test-1.jar:?]
        at org.apache.camel.support.ProcessorEndpoint$1.process(ProcessorEndpoint.java:61) ~[test-1.jar:?]
        at org.apache.camel.support.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:65) ~[test-1.jar:?]
        at org.apache.camel.processor.SendProcessor.process(SendProcessor.java:210) ~[test-1.jar:?]
        at org.apache.camel.impl.engine.CamelInternalProcessor.processNonTransacted(CamelInternalProcessor.java:354) ~[test-1.jar:?]
        at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:330) ~[test-1.jar:?]
        at org.apache.camel.processor.Pipeline$PipelineTask.run(Pipeline.java:102) ~[test-1.jar:?]
        at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.doRun(DefaultReactiveExecutor.java:199) ~[test-1.jar:?]
        at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.executeReactiveWork(DefaultReactiveExecutor.java:189) ~[test-1.jar:?]
        at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.tryExecuteReactiveWork(DefaultReactiveExecutor.java:166) ~[test-1.jar:?]
        at org.apache.camel.impl.engine.DefaultReactiveExecutor$Worker.schedule(DefaultReactiveExecutor.java:148) ~[test-1.jar:?]
        at org.apache.camel.impl.engine.DefaultReactiveExecutor.scheduleMain(DefaultReactiveExecutor.java:59) ~[test-1.jar:?]
        at org.apache.camel.processor.Pipeline.process(Pipeline.java:163) ~[test-1.jar:?]
        at org.apache.camel.impl.engine.CamelInternalProcessor.processNonTransacted(CamelInternalProcessor.java:354) ~[test-1.jar:?]
        at org.apache.camel.impl.engine.CamelInternalProcessor.process(CamelInternalProcessor.java:330) ~[test-1.jar:?]
        at org.apache.camel.impl.engine.DefaultAsyncProcessorAwaitManager.process(DefaultAsyncProcessorAwaitManager.java:82) ~[test-1.jar:?]
        at org.apache.camel.support.AsyncProcessorSupport.process(AsyncProcessorSupport.java:32) ~[test-1.jar:?]
        at org.apache.camel.component.platform.http.vertx.VertxPlatformHttpConsumer.processExchange(VertxPlatformHttpConsumer.java:236) ~[test-1.jar:?]
        at org.apache.camel.component.platform.http.vertx.VertxPlatformHttpConsumer.lambda$handleRequest$1(VertxPlatformHttpConsumer.java:204) ~[test-1.jar:?]
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$0(ContextImpl.java:177) ~[test-1.jar:?]
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:276) ~[test-1.jar:?]
        at io.vertx.core.impl.ContextImpl.lambda$internalExecuteBlocking$2(ContextImpl.java:209) ~[test-1.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [test-1.jar:?]
        at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
```
</details>
<br/>
```

**Comment by davsclaus** [comment]
okay so when you build and deploy then karavan does an export, and it must then be able to include that json file in the build.

**Comment by davsclaus** [comment]
Can you try adding to `application.properties`

```
camel.jbang.classpathFiles=my-validator.json
```

And then do a build and deploy

**Comment by davsclaus** [comment]
If I try your example I can have it working.
And I also see that the my-validator.json is included in the export. But I run Camel 4.5+.

```
curl -i -X POST http://0.0.0.0:8080/test -d @sample.json -H "Content-Type: application/json"                                             27s
HTTP/1.1 200 OK
Accept: */*
User-Agent: curl/8.1.2
transfer-encoding: chunked
Content-Type: application/json
```
You can try the new Karavan 4.5.0 release

**Comment by davsclaus** [comment]
closing old ticket
