### ISSUE TITLE
Docker install fails

### ISSUE THREAD

**Issue by mechatronics123** [apache/camel-karavan#1164]
**Docker compose fails with :**

> docker compose up
> WARN[0000] The "KARAVAN_GIT_REPOSITORY" variable is not set. Defaulting to a blank string.
> WARN[0000] The "KARAVAN_GIT_USERNAME" variable is not set. Defaulting to a blank string.
> WARN[0000] The "KARAVAN_GIT_PASSWORD" variable is not set. Defaulting to a blank string.
> [+] Running 0/2
>  ⠙ karavan Pulling                                                                                                 0.2s
>  ⠙ registry Pulling                                                                                                0.2s
> error getting credentials - err: fork/exec /usr/bin/docker-credential-desktop.exe: exec format error, out: ``

**Docker gitea fails with:**

> validating /mnt/c/Docker/karavan-docker/docker-compose-gitea.yaml: services.karavan Additional property restart_policy is not allowed

**any solutions?**

**Thanks**

**Comment by dorachenxiW** [comment]
Hi I have the similar problem. I am very new to karavan and tried to follow the youtube video of building a demo integration, however, I seem to not have the right environment variables. I am confused about the KARAVAN_GIT_REPOSITORY, KARAVAN_GIT_USERNAME and KARAVAN_GIT_PASSWORD. Are they supposed to be my own github repository or the github.com/apache/camel-karavan? Thank you.
![image](https://github.com/apache/camel-karavan/assets/125512384/5a15bee3-a9f0-48da-8451-91fc2c93850b)

**Comment by mechatronics123** [comment]
Hi,
it is this one from "camel-karavan/docs/WEB_DOCKER.md":

https://github.com/apache/camel-karavan/blob/main/docs/install/karavan-docker/docker-compose.yaml

**Comment by mgubaidullin** [comment]
These parameters to connect to your git repository to store your projects.

**Comment by vebera** [comment]
```log

	... 10 more
Caused by: io.quarkus.runtime.configuration.ConfigurationException: Failed to load config value of type class java.lang.String for: karavan.git.repository

		... 9 more
		at io.quarkus.arc.runtime.ConfigRecorder.validateConfigProperties(ConfigRecorder.java:60)
		at io.smallrye.config.inject.ConfigProducerUtil.getValue(ConfigProducerUtil.java:100)
		at io.smallrye.config.SmallRyeConfig.convertValue(SmallRyeConfig.java:371)
	Suppressed: java.util.NoSuchElementException: SRCFG00040: The config property karavan.git.repository is defined as the empty String ("") which the following Converter considered to be null: io.smallrye.config.Converters$BuiltInConverter
	... 7 more
	at io.quarkus.deployment.steps.ConfigBuildStep$validateConfigValues1665125174.deploy(Unknown Source)
	at io.quarkus.deployment.steps.ConfigBuildStep$validateConfigValues1665125174.deploy_0(Unknown Source)
	at io.quarkus.arc.runtime.ConfigRecorder.validateConfigProperties(ConfigRecorder.java:70)
Caused by: jakarta.enterprise.inject.spi.DeploymentException: io.quarkus.runtime.configuration.ConfigurationException: Failed to load config value of type class java.lang.String for: karavan.git.repository
```

better to wrap it with try...catch with giving a meaninful error message.
