### ISSUE TITLE
Do catch generating exception

### ISSUE THREAD

**Issue by pierpaolo1** [apache/camel-karavan#1420]
### Describe the bug

I get this exception:
Unsupported field: when
 in file:karavan-esb.camel.yaml, line 387, column 21:
                        id: when-e836
                        ^

### Steps to reproduce the behavior

1. add do Try componente
2. add do Catch component

![immagine](https://github.com/user-attachments/assets/3b65df66-1e14-4f51-a113-d6d00c30cbbd)

3. configure do Catch
![immagine](https://github.com/user-attachments/assets/fb75a954-eae7-494b-81ea-4098db2c1fb6)

4. launch: jbang "-Dcamel.jbang.version=4.7.0" camel@apache/camel run * 
5. get the exception 

Here an extract of generated yaml:
![immagine](https://github.com/user-attachments/assets/a8910689-44fd-4a95-a39f-0380af51a443)

### Variant

Vs Code Extension

### Container Management (if applicable)

None

### Operating System (if applicable)

Linux

### Version

4.7.0

### Relevant log output

```shell
Unsupported field: when
 in file:karavan-esb.camel.yaml, line 387, column 21:
                        id: when-e836
                        ^

        at org.apache.camel.dsl.yaml.common.YamlDeserializerBase.handleUnknownProperty(YamlDeserializerBase.java:134)
        at org.apache.camel.dsl.yaml.common.YamlDeserializerBase.setProperties(YamlDeserializerBase.java:128)
        at org.apache.camel.dsl.yaml.common.YamlDeserializerBase.construct(YamlDeserializerBase.java:67)
        at org.apache.camel.dsl.yaml.common.YamlDeserializationContext.lambda$resolve$0(YamlDeserializationContext.java:157)
        at org.apache.camel.dsl.yaml.common.YamlDeserializerSupport.asType(YamlDeserializerSupport.java:344)
        at org.apache.camel.dsl.yaml.deserializers.ModelDeserializers$CatchDefinitionDeserializer.setProperty(ModelDeserializers.java:1941)
        at org.apache.camel.dsl.yaml.deserializers.ModelDeserializers$CatchDefinitionDeserializer.setProperty(ModelDeserializers.java:1890)
        at org.apache.camel.dsl.yaml.common.YamlDeserializerBase.setProperties(YamlDeserializerBase.java:127)
        at org.apache.camel.dsl.yaml.common.YamlDeserializerBase.construct(YamlDeserializerBase.java:67)
        at org.apache.camel.dsl.yaml.common.YamlDeserializationContext.lambda$resolve$0(YamlDeserializationContext.java:157)
        at org.apache.camel.dsl.yaml.common.YamlDeserializerSupport.asType(YamlDeserializerSupport.java:344)
        at org.apache.camel.dsl.yaml.common.YamlDeserializerSupport.asCollection(YamlDeserializerSupport.java:322)
        at org.apache.camel.dsl.yaml.common.YamlDeserializerSupport.asFlatCollection(YamlDeserializerSupport.java:298)
        at org.apache.camel.dsl.yaml.common.YamlDeserializerSupport.asFlatList(YamlDeserializerSupport.java:277)
        at org.apache.camel.dsl.yaml.deserializers.ModelDeserializers$TryDefinitionDeserializer.setProperty(ModelDeserializers.java:19061)
        at org.apache.camel.dsl.yaml.deserializers.ModelDeserializers$TryDefinitionDeserializer.setProperty(ModelDeserializers.java:19025)
        at org.apache.camel.dsl.yaml.common.YamlDeserializerBase.setProperties(YamlDeserializerBase.java:127)
        at org.apache.camel.dsl.yaml.common.YamlDeserializerBase.construct(YamlDeserializerBase.java:67)
        at org.apache.camel.dsl.yaml.common.YamlDeserializationContext.lambda$resolve$1(YamlDeserializationContext.java:198)
        at org.apache.camel.dsl.yaml.deserializers.ProcessorDefinitionDeserializer.construct(ProcessorDefinitionDeserializer.java:37)
        at org.apache.camel.dsl.yaml.common.YamlDeserializationContext.lambda$resolve$0(YamlDeserializationContext.java:157)
        at org.apache.camel.dsl.yaml.common.YamlDeserializerSupport.asType(YamlDeserializerSupport.java:344)
        at org.apache.camel.dsl.yaml.common.YamlDeserializerSupport.asCollection(YamlDeserializerSupport.java:322)
        at org.apache.camel.dsl.yaml.common.YamlDeserializerSupport.asFlatCollection(YamlDeserializerSupport.java:298)
        at org.apache.camel.dsl.yaml.common.YamlDeserializerSupport.asFlatList(YamlDeserializerSupport.java:277)
        at org.apache.camel.dsl.yaml.common.YamlDeserializerSupport.setStepsFlowMode(YamlDeserializerSupport.java:400)
        at org.apache.camel.dsl.yaml.common.YamlDeserializerSupport.setSteps(YamlDeserializerSupport.java:395)
        at org.apache.camel.dsl.yaml.common.YamlSupport.creteEndpointUri(YamlSupport.java:179)
        at org.apache.camel.dsl.yaml.deserializers.FromDefinitionDeserializer.construct(FromDefinitionDeserializer.java:84)
        at org.apache.camel.dsl.yaml.common.YamlDeserializationContext.lambda$resolve$0(YamlDeserializationContext.java:157)
        at org.apache.camel.dsl.yaml.common.YamlDeserializerSupport.asType(YamlDeserializerSupport.java:344)
        at org.apache.camel.dsl.yaml.deserializers.RouteDefinitionDeserializer.setProperties(RouteDefinitionDeserializer.java:157)
        at org.apache.camel.dsl.yaml.deserializers.RouteDefinitionDeserializer.setProperties(RouteDefinitionDeserializer.java:37)
        at org.apache.camel.dsl.yaml.common.YamlDeserializerBase.construct(YamlDeserializerBase.java:67)
        at org.apache.camel.dsl.yaml.common.YamlDeserializationContext.lambda$resolve$1(YamlDeserializationContext.java:198)
        at org.apache.camel.dsl.yaml.YamlRoutesBuilderLoader$1.configure(YamlRoutesBuilderLoader.java:170)
        at org.apache.camel.builder.RouteBuilder.checkInitialized(RouteBuilder.java:788)
        at org.apache.camel.builder.RouteBuilder.configureRoutes(RouteBuilder.java:733)
        at org.apache.camel.builder.RouteBuilder.prepareModel(RouteBuilder.java:649)
        at org.apache.camel.builder.RouteBuilder.addRoutesToCamelContext(RouteBuilder.java:667)
        at org.apache.camel.impl.engine.AbstractCamelContext.addRoutes(AbstractCamelContext.java:988)
        at org.apache.camel.main.RoutesConfigurer.addDiscoveredRoutes(RoutesConfigurer.java:254)
        at org.apache.camel.main.RoutesConfigurer.configureRoutes(RoutesConfigurer.java:236)
        at org.apache.camel.main.BaseMainSupport.configureRoutes(BaseMainSupport.java:618)
        at org.apache.camel.main.BaseMainSupport.postProcessCamelContext(BaseMainSupport.java:700)
        at org.apache.camel.main.MainSupport.initCamelContext(MainSupport.java:339)
        at org.apache.camel.main.KameletMain.doInit(KameletMain.java:355)
        at org.apache.camel.support.service.BaseService.init(BaseService.java:78)
        at org.apache.camel.support.service.BaseService.start(BaseService.java:105)
        at org.apache.camel.dsl.jbang.core.commands.Run.runKameletMain(Run.java:1336)
        at org.apache.camel.dsl.jbang.core.commands.Run.run(Run.java:873)
        at org.apache.camel.dsl.jbang.core.commands.Run.doCall(Run.java:320)
        at org.apache.camel.dsl.jbang.core.commands.CamelCommand.call(CamelCommand.java:71)
        at org.apache.camel.dsl.jbang.core.commands.CamelCommand.call(CamelCommand.java:37)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2045)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at picocli.CommandLine.execute(CommandLine.java:2174)
        at org.apache.camel.dsl.jbang.core.commands.CamelJBangMain.run(CamelJBangMain.java:168)
        at org.apache.camel.dsl.jbang.core.commands.CamelJBangMain.run(CamelJBangMain.java:61)
        at main.CamelJBang.main(CamelJBang.java:36)
```

**Comment by pierpaolo1** [comment]
After some trials, I noticed some dirty code in yaml:
![immagine](https://github.com/user-attachments/assets/6a99caa7-8328-4972-914f-ce2d4bf8ad4c)
