### ISSUE TITLE
Error on deploy in serverless mode

### ISSUE THREAD

**Issue by edivanteixeira** [apache/camel-karavan#194]
I receive error on try deploy any routes by serverless mode in minikube.

```yaml
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: logtest.yaml
spec:
  flows:
    - route:
        from:
          uri: timer:tick
          steps:
            - log:
                message: Hello world
                logName: teste
```

Camel K Client 1.8.0

pod logs:

```shell
exec java -cp ./resources:/etc/camel/application.properties:/etc/camel/conf.d/_resources:/etc/camel/resources:/etc/camel/sources/camel-k-embedded-flow.yaml:dependencies/app/camel-k-integration-1.8.0.jar:dependencies/lib/boot/io.quarkus.quarkus-bootstrap-runner-2.6.0.Final.jar:dependencies/lib/boot/io.quarkus.quarkus-development-mode-spi-2.6.0.Final.jar:dependencies/lib/boot/io.smallrye.common.smallrye-common-io-1.8.0.jar:dependencies/lib/boot/org.glassfish.jakarta.json-1.1.6.jar:dependencies/lib/boot/org.graalvm.sdk.graal-sdk-21.3.0.jar:dependencies/lib/boot/org.jboss.logging.jboss-logging-3.4.2.Final.jar:dependencies/lib/boot/org.jboss.logmanager.jboss-logmanager-embedded-1.0.9.jar:dependencies/lib/boot/org.wildfly.common.wildfly-common-1.5.4.Final-format-001.jar:dependencies/lib/main/io.quarkus.arc.arc-2.6.0.Final.jar:dependencies/lib/main/io.quarkus.quarkus-arc-2.6.0.Final.jar:dependencies/lib/main/io.quarkus.quarkus-core-2.6.0.Final.jar:dependencies/lib/main/io.quarkus.quarkus-fs-util-0.0.3.jar:dependencies/lib/main/io.quarkus.quarkus-jsonp-2.6.0.Final.jar:dependencies/lib/main/io.quarkus.quarkus-logging-json-2.6.0.Final.jar:dependencies/lib/main/io.smallrye.common.smallrye-common-annotation-1.8.0.jar:dependencies/lib/main/io.smallrye.common.smallrye-common-classloader-1.8.0.jar:dependencies/lib/main/io.smallrye.common.smallrye-common-constraint-1.8.0.jar:dependencies/lib/main/io.smallrye.common.smallrye-common-expression-1.8.0.jar:dependencies/lib/main/io.smallrye.common.smallrye-common-function-1.8.0.jar:dependencies/lib/main/io.smallrye.config.smallrye-config-2.7.0.jar:dependencies/lib/main/io.smallrye.config.smallrye-config-common-2.7.0.jar:dependencies/lib/main/io.smallrye.config.smallrye-config-core-2.7.0.jar:dependencies/lib/main/jakarta.annotation.jakarta.annotation-api-1.3.5.jar:dependencies/lib/main/jakarta.el.jakarta.el-api-3.0.3.jar:dependencies/lib/main/jakarta.enterprise.jakarta.enterprise.cdi-api-2.0.2.jar:dependencies/lib/main/jakarta.inject.jakarta.inject-api-1.0.jar:dependencies/lib/main/jakarta.interceptor.jakarta.interceptor-api-1.2.5.jar:dependencies/lib/main/jakarta.transaction.jakarta.transaction-api-1.3.3.jar:dependencies/lib/main/org.apache.camel.camel-api-3.14.0.jar:dependencies/lib/main/org.apache.camel.camel-base-3.14.0.jar:dependencies/lib/main/org.apache.camel.camel-base-engine-3.14.0.jar:dependencies/lib/main/org.apache.camel.camel-bean-3.14.0.jar:dependencies/lib/main/org.apache.camel.camel-componentdsl-3.14.0.jar:dependencies/lib/main/org.apache.camel.camel-core-catalog-3.14.0.jar:dependencies/lib/main/org.apache.camel.camel-core-engine-3.14.0.jar:dependencies/lib/main/org.apache.camel.camel-core-languages-3.14.0.jar:dependencies/lib/main/org.apache.camel.camel-core-model-3.14.0.jar:dependencies/lib/main/org.apache.camel.camel-core-processor-3.14.0.jar:dependencies/lib/main/org.apache.camel.camel-core-reifier-3.14.0.jar:dependencies/lib/main/org.apache.camel.camel-dsl-support-3.14.0.jar:dependencies/lib/main/org.apache.camel.camel-endpointdsl-3.14.0.jar:dependencies/lib/main/org.apache.camel.camel-main-3.14.0.jar:dependencies/lib/main/org.apache.camel.camel-management-api-3.14.0.jar:dependencies/lib/main/org.apache.camel.camel-microprofile-config-3.14.0.jar:dependencies/lib/main/org.apache.camel.camel-support-3.14.0.jar:dependencies/lib/main/org.apache.camel.camel-timer-3.14.0.jar:dependencies/lib/main/org.apache.camel.camel-tooling-model-3.14.0.jar:dependencies/lib/main/org.apache.camel.camel-util-3.14.0.jar:dependencies/lib/main/org.apache.camel.camel-util-json-3.14.0.jar:dependencies/lib/main/org.apache.camel.camel-yaml-dsl-3.14.0.jar:dependencies/lib/main/org.apache.camel.camel-yaml-dsl-common-3.14.0.jar:dependencies/lib/main/org.apache.camel.camel-yaml-dsl-deserializers-3.14.0.jar:dependencies/lib/main/org.apache.camel.k.camel-k-core-1.11.0.jar:dependencies/lib/main/org.apache.camel.k.camel-k-core-api-1.11.0.jar:dependencies/lib/main/org.apache.camel.k.camel-k-core-support-1.11.0.jar:dependencies/lib/main/org.apache.camel.k.camel-k-runtime-1.11.0.jar:dependencies/lib/main/org.apache.camel.quarkus.camel-quarkus-bean-2.6.0.jar:dependencies/lib/main/org.apache.camel.quarkus.camel-quarkus-core-2.6.0.jar:dependencies/lib/main/org.apache.camel.quarkus.camel-quarkus-timer-2.6.0.jar:dependencies/lib/main/org.apache.camel.quarkus.camel-quarkus-yaml-dsl-2.6.0.jar:dependencies/lib/main/org.eclipse.microprofile.config.microprofile-config-api-2.0.jar:dependencies/lib/main/org.eclipse.microprofile.context-propagation.microprofile-context-propagation-api-1.2.jar:dependencies/lib/main/org.jboss.logging.jboss-logging-annotations-2.2.1.Final.jar:dependencies/lib/main/org.jboss.slf4j.slf4j-jboss-logmanager-1.1.0.Final.jar:dependencies/lib/main/org.jboss.spec.javax.xml.bind.jboss-jaxb-api_2.3_spec-2.0.0.Final.jar:dependencies/lib/main/org.jboss.threads.jboss-threads-3.4.2.Final.jar:dependencies/lib/main/org.slf4j.slf4j-api-1.7.30.jar:dependencies/lib/main/org.snakeyaml.snakeyaml-engine-2.3.jar:dependencies/quarkus-app-dependencies.txt:dependencies/quarkus-run.jar:dependencies/quarkus/generated-bytecode.jar:dependencies/quarkus/quarkus-application.dat io.quarkus.bootstrap.runner.QuarkusEntryPoint
[38;5;145m2022-02-15 17:43:08,911[39m[38;5;188m [39m[38;5;107mINFO [39m[38;5;188m [[39m[38;5;69morg.apa.cam.k.Runtime[39m[38;5;188m] ([39m[38;5;71mmain[39m[38;5;188m) [39m[38;5;151mApache Camel K Runtime 1.11.0[39m[38;5;203m[39m[38;5;227m
[39m[38;5;145m2022-02-15 17:43:08,957[39m[38;5;188m [39m[38;5;107mINFO [39m[38;5;188m [[39m[38;5;69morg.apa.cam.qua.cor.CamelBootstrapRecorder[39m[38;5;188m] ([39m[38;5;71mmain[39m[38;5;188m) [39m[38;5;151m[39mBootstrap runtime: [38;5;188morg.apache.camel.quarkus.main.CamelMainRuntime[39m[39m[38;5;203m[39m[38;5;227m
[39m[38;5;145m2022-02-15 17:43:09,056[39m[38;5;188m [39m[38;5;107mINFO [39m[38;5;188m [[39m[38;5;69morg.apa.cam.k.lis.SourcesConfigurer[39m[38;5;188m] ([39m[38;5;71mmain[39m[38;5;188m) [39m[38;5;151mLoading routes from: SourceDefinition{name='camel-k-embedded-flow', language='yaml', type='source', location='file:/etc/camel/sources/camel-k-embedded-flow.yaml', }[39m[38;5;203m[39m[38;5;227m
[39m[38;5;145m2022-02-15 17:43:09,270[39m[38;5;188m [39m[38;5;203mERROR[39m[38;5;188m [[39m[38;5;69morg.apa.cam.qua.mai.CamelMainRuntime[39m[38;5;188m] ([39m[38;5;71mmain[39m[38;5;188m) [39m[38;5;151mFailed to start application[39m[38;5;203m: java.lang.IllegalArgumentException: Unsupported field: steps
at org.apache.camel.dsl.yaml.common.YamlSupport.creteEndpointUri(YamlSupport.java:248)
at org.apache.camel.dsl.yaml.deserializers.FromDefinitionDeserializer.construct(FromDefinitionDeserializer.java:38)
at org.apache.camel.dsl.yaml.common.YamlDeserializationContext$1.construct(YamlDeserializationContext.java:179)
at org.apache.camel.dsl.yaml.common.YamlDeserializerSupport.asType(YamlDeserializerSupport.java:351)
at org.apache.camel.dsl.yaml.deserializers.RouteDefinitionDeserializer.setProperties(RouteDefinitionDeserializer.java:78)
at org.apache.camel.dsl.yaml.deserializers.RouteDefinitionDeserializer.setProperties(RouteDefinitionDeserializer.java:32)
at org.apache.camel.dsl.yaml.common.YamlDeserializerBase.construct(YamlDeserializerBase.java:51)
at org.apache.camel.dsl.yaml.common.YamlDeserializationContext$2.construct(YamlDeserializationContext.java:221)
at org.apache.camel.dsl.yaml.YamlRoutesBuilderLoader$1.configuration(YamlRoutesBuilderLoader.java:145)
at org.apache.camel.builder.RouteConfigurationBuilder.addRouteConfigurationsToCamelContext(RouteConfigurationBuilder.java:76)
at org.apache.camel.impl.engine.AbstractCamelContext.addRoutesConfigurations(AbstractCamelContext.java:1170)
at org.apache.camel.main.RoutesConfigurer.addDiscoveredRoutes(RoutesConfigurer.java:228)
at org.apache.camel.main.RoutesConfigurer.configureRoutes(RoutesConfigurer.java:209)
at org.apache.camel.quarkus.main.CamelMain.configureRoutes(CamelMain.java:70)
at org.apache.camel.main.BaseMainSupport.postProcessCamelContext(BaseMainSupport.java:555)
at org.apache.camel.quarkus.main.CamelMain.initCamelContext(CamelMain.java:116)
at org.apache.camel.quarkus.main.CamelMain.doInit(CamelMain.java:86)
at org.apache.camel.support.service.BaseService.init(BaseService.java:83)
at org.apache.camel.quarkus.main.CamelMain.startEngine(CamelMain.java:137)
at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:49)
at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:45)
at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot173480958.deploy_0(Unknown Source)
at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot173480958.deploy(Unknown Source)
at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
at io.quarkus.runtime.Application.start(Application.java:101)
at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:104)
at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
at io.quarkus.runner.GeneratedMain.main(Unknown Source)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:53)
at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:28)
[39m[38;5;227m
[39m[38;5;145m2022-02-15 17:43:09,321[39m[38;5;188m [39m[38;5;203mERROR[39m[38;5;188m [[39m[38;5;69mio.qua.run.Application[39m[38;5;188m] ([39m[38;5;71mmain[39m[38;5;188m) [39m[38;5;151mFailed to start application (with profile prod)[39m[38;5;203m: java.lang.IllegalArgumentException: Unsupported field: steps
at org.apache.camel.dsl.yaml.common.YamlSupport.creteEndpointUri(YamlSupport.java:248)
at org.apache.camel.dsl.yaml.deserializers.FromDefinitionDeserializer.construct(FromDefinitionDeserializer.java:38)
at org.apache.camel.dsl.yaml.common.YamlDeserializationContext$1.construct(YamlDeserializationContext.java:179)
at org.apache.camel.dsl.yaml.common.YamlDeserializerSupport.asType(YamlDeserializerSupport.java:351)
at org.apache.camel.dsl.yaml.deserializers.RouteDefinitionDeserializer.setProperties(RouteDefinitionDeserializer.java:78)
at org.apache.camel.dsl.yaml.deserializers.RouteDefinitionDeserializer.setProperties(RouteDefinitionDeserializer.java:32)
at org.apache.camel.dsl.yaml.common.YamlDeserializerBase.construct(YamlDeserializerBase.java:51)
at org.apache.camel.dsl.yaml.common.YamlDeserializationContext$2.construct(YamlDeserializationContext.java:221)
at org.apache.camel.dsl.yaml.YamlRoutesBuilderLoader$1.configuration(YamlRoutesBuilderLoader.java:145)
at org.apache.camel.builder.RouteConfigurationBuilder.addRouteConfigurationsToCamelContext(RouteConfigurationBuilder.java:76)
at org.apache.camel.impl.engine.AbstractCamelContext.addRoutesConfigurations(AbstractCamelContext.java:1170)
at org.apache.camel.main.RoutesConfigurer.addDiscoveredRoutes(RoutesConfigurer.java:228)
at org.apache.camel.main.RoutesConfigurer.configureRoutes(RoutesConfigurer.java:209)
at org.apache.camel.quarkus.main.CamelMain.configureRoutes(CamelMain.java:70)
at org.apache.camel.main.BaseMainSupport.postProcessCamelContext(BaseMainSupport.java:555)
at org.apache.camel.quarkus.main.CamelMain.initCamelContext(CamelMain.java:116)
at org.apache.camel.quarkus.main.CamelMain.doInit(CamelMain.java:86)
at org.apache.camel.support.service.BaseService.init(BaseService.java:83)
at org.apache.camel.quarkus.main.CamelMain.startEngine(CamelMain.java:137)
at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:49)
at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:45)
at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot173480958.deploy_0(Unknown Source)
at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot173480958.deploy(Unknown Source)
at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
at io.quarkus.runtime.Application.start(Application.java:101)
at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:104)
at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
at io.quarkus.runner.GeneratedMain.main(Unknown Source)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:53)
at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:28)
[39m[38;5;227m
[39m
```

**Comment by davsclaus** [comment]
Camel K needs to update to Camel 3.15 or later. They are not there yet.

**Comment by davsclaus** [comment]
Yeah you would need to wait for camel-k 1.9.x

**Comment by edivanteixeira** [comment]
thanks

**Comment by davsclaus** [comment]
We are still working on karavan and camel at the same time in collaboration - as karavan helps find out some minor mistakes and other things to fix/improve in camel core / yaml dsl and as such you need to be tracking latest releases

We also have some fixes that needs Camel 3.16.x and so on.

An older version of karavan may run with camel k 1.8.x.

**Comment by mikeintoch** [comment]
Will be there retrocompatibility with the old integration CRD?

**Comment by davsclaus** [comment]
No there will not be
