### ISSUE TITLE
Could not find artifact org.apache.camel:camel-bom:pom:3.16.0 in apache (https://repository.apache.org/snapshots)

### ISSUE THREAD

**Issue by bheuse** [apache/camel-karavan#284]
**Describe the bug**
Running Karavan in Visual Studio Code on Ubuntu 18.04
Apache Camel Karavan runs jbang :
jbang  run  -Dcamel.jbang.version=3.16.0 camel@apache/camel

user@machine:~/VSCodeProjects/Karavan$ jbang --verbose run --verbose -Dcamel.jbang.version=3.16.0 camel@apache/camel 
[jbang] Reading aliases from /home/bheuse/.jbang/implicit-catalog.json
[jbang] Retrieved file from cache https://raw.githubusercontent.com/apache/camel/HEAD/jbang-catalog.json = /home/bheuse/.jbang/cache/urls/0386409827e5d8ef377cbe8d6d4043c23fa73330d1f74bfca89a74a371947769/jbang-catalog.json
[jbang] Obtained catalog from https://github.com/apache/camel/blob/HEAD/jbang-catalog.json
[jbang] Reading aliases from /home/bheuse/.jbang/cache/urls/0386409827e5d8ef377cbe8d6d4043c23fa73330d1f74bfca89a74a371947769/jbang-catalog.json
[jbang] Reading aliases from /home/bheuse/.jbang/jbang-catalog.json
[jbang] Retrieved file from cache https://raw.githubusercontent.com/apache/camel/HEAD/jbang-catalog.json = /home/bheuse/.jbang/cache/urls/0386409827e5d8ef377cbe8d6d4043c23fa73330d1f74bfca89a74a371947769/jbang-catalog.json
[jbang] Obtained catalog from https://github.com/apache/camel/blob/HEAD/jbang-catalog.json
[jbang] Downloaded file https://raw.githubusercontent.com/apache/camel/HEAD/dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java
[jbang] System Java version detected as 11
[jbang] System Java version matches requested version 11
[jbang] Resolving dependencies...
[jbang]     Resolving org.apache.camel:camel-bom:3.16.0@pom...Apr 07, 2022 12:29:29 PM org.jboss.shrinkwrap.resolver.impl.maven.logging.LogTransferListener transferFailed
WARNING: Failed downloading org/apache/camel/camel-bom/3.16.0/camel-bom-3.16.0.pom from https://repository.apache.org/snapshots/. Reason: 
org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.apache.camel:camel-bom:pom:3.16.0 in apache (https://repository.apache.org/snapshots)
Apr 07, 2022 12:29:29 PM org.jboss.shrinkwrap.resolver.impl.maven.logging.LogRepositoryListener artifactDescriptorMissing
WARNING: Missing artifact descriptor for org.apache.camel:camel-bom:pom:3.16.0
Apr 07, 2022 12:29:29 PM org.jboss.shrinkwrap.resolver.impl.maven.logging.LogTransferListener transferFailed
WARNING: Failed downloading org/apache/camel/camel-bom/3.16.0/camel-bom-3.16.0.pom from https://repository.apache.org/snapshots/. Reason: 
org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.apache.camel:camel-bom:pom:3.16.0 in apache (https://repository.apache.org/snapshots)
[jbang] Deleting /home/bheuse/.jbang/cache/jars/CamelJBang.java.47e72095fc0bcf1d1a27a356a941c9469bea13a4fe5c9fc9205f944976e860a9
[jbang] [ERROR] Could not resolve dependency
dev.jbang.ExitException: Could not resolve dependency
        at dev.jbang.DependencyUtil.lambda$resolveDependenciesViaAether$3(DependencyUtil.java:145)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at dev.jbang.DependencyUtil.resolveDependenciesViaAether(DependencyUtil.java:152)
        at dev.jbang.DependencyUtil.resolveDependencies(DependencyUtil.java:88)
        at dev.jbang.DependencyUtil.resolveDependencies(DependencyUtil.java:39)
        at dev.jbang.Script.resolveClassPath(Script.java:295)
        at dev.jbang.cli.BaseBuildCommand.buildJar(BaseBuildCommand.java:153)
        at dev.jbang.cli.BaseBuildCommand.build(BaseBuildCommand.java:129)
        at dev.jbang.cli.Run.prepareArtifacts(Run.java:70)
        at dev.jbang.cli.Run.doCall(Run.java:59)
        at dev.jbang.cli.BaseCommand.call(BaseCommand.java:80)
        at dev.jbang.cli.BaseCommand.call(BaseCommand.java:12)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
        at picocli.CommandLine.access$1200(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at dev.jbang.Main.main(Main.java:14)
Caused by: org.jboss.shrinkwrap.resolver.api.NoResolvedResultException: Unable to collect/resolve dependency tree for a resolution due to: Could not find artifact org.apache.camel:camel-bom:pom:3.16.0 in apache (https://repository.apache.org/snapshots), caused by: Could not find artifact org.apache.camel:camel-bom:pom:3.16.0 in apache (https://repository.apache.org/snapshots)
        at org.jboss.shrinkwrap.resolver.impl.maven.MavenWorkingSessionImpl.wrapException(MavenWorkingSessionImpl.java:503)
        at org.jboss.shrinkwrap.resolver.impl.maven.MavenWorkingSessionImpl.resolveDependencies(MavenWorkingSessionImpl.java:242)
        at org.jboss.shrinkwrap.resolver.impl.maven.MavenStrategyStageBaseImpl.using(MavenStrategyStageBaseImpl.java:70)
        at org.jboss.shrinkwrap.resolver.impl.maven.MavenStrategyStageBaseImpl.withTransitivity(MavenStrategyStageBaseImpl.java:52)
        at org.jboss.shrinkwrap.resolver.impl.maven.MavenStrategyStageBaseImpl.withTransitivity(MavenStrategyStageBaseImpl.java:39)
        at dev.jbang.DependencyUtil.lambda$resolveDependenciesViaAether$3(DependencyUtil.java:139)
        ... 25 more
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact org.apache.camel:camel-bom:pom:3.16.0 in apache (https://repository.apache.org/snapshots)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:357)
        at org.jboss.shrinkwrap.resolver.impl.maven.bootstrap.MavenRepositorySystem.resolveDependencies(MavenRepositorySystem.java:121)
        at org.jboss.shrinkwrap.resolver.impl.maven.MavenWorkingSessionImpl.resolveDependencies(MavenWorkingSessionImpl.java:239)
        ... 29 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.apache.camel:camel-bom:pom:3.16.0 in apache (https://repository.apache.org/snapshots)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:424)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:229)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:340)
        ... 31 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.apache.camel:camel-bom:pom:3.16.0 in apache (https://repository.apache.org/snapshots)
        at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:48)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:369)
        at org.eclipse.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:75)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector$DirectExecutor.execute(BasicRepositoryConnector.java:644)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector.get(BasicRepositoryConnector.java:262)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:499)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:401)
        ... 33 more
[jbang] If you believe this a bug in jbang open issue at https://github.com/jbangdev/jbang/issues

**Comment by davsclaus** [comment]
Have you run jbang / camel-jbang before?

Smells like you need to run it with --fresh or re-install jbang

as it may be you have an oudated cameljbang in the jbang cache. The correct has maven central as the repo to download from first where 3.16.0 is located
https://repo.maven.apache.org/maven2/org/apache/camel/camel-bom/3.16.0/

**Comment by bheuse** [comment]
I had installed jbang from Ubuntu store - it may be an outdated version indeed.
Updated from jbang site - works now.
You can close the issue.
Maybe update the install notes ...

**Comment by bheuse** [comment]
Paphos

**Comment by bheuse** [comment]
I had installed jbang from Ubuntu store - it may be an outdated version indeed.
Updated from jbang site - works now.
You can close the issue.
Maybe update the install notes ...
