### ISSUE TITLE
[VS Code Server] Unable to resolve nonexistent file error when trying to start with `Karavan: Run file ` from title bar

### ISSUE THREAD

**Issue by apupier** [apache/camel-karavan#372]
```
[2022-06-17 15:13:02.961] [window] [error] Unable to read file 'vscode-remote://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/checode/checode-linux-libc/application.properties' (Error: Unable to resolve nonexistent file 'vscode-remote://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/checode/checode-linux-libc/application.properties'): EntryNotFound (FileSystemError): Unable to read file 'vscode-remote://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/checode/checode-linux-libc/application.properties' (Error: Unable to resolve nonexistent file 'vscode-remote://che-dogfooding.apps.che-dev.x6e0.p1.openshiftapps.com/checode/checode-linux-libc/application.properties')
	at Function._handleError (/checode/checode-linux-libc/out/vs/workbench/api/node/extensionHostProcess.js:85:121629)
	at Object.readFile (/checode/checode-linux-libc/out/vs/workbench/api/node/extensionHostProcess.js:85:120543)
```

![TitleBar-runFile-notworking-karavan-indevspaces](https://user-images.githubusercontent.com/1105127/174305691-384e3380-0f8a-43da-b440-330ddde75e1e.gif)

**Comment by mgubaidullin** [comment]
fixed in upcoming 3.18.5
