### ISSUE TITLE
java.lang.NullPointerException at org.apache.camel.karavan.service.GitService.getGitConfig(GitService.java:82)

### ISSUE THREAD

**Issue by zetfactor** [apache/camel-karavan#513]
**Environment:**
Provider: RKE1
Kubernetes Version: v1.24.4
Local Machine

Followed the deployment instructions step by step for Minikube, I have tried editing the karavan-secret.yaml by modifying GitHub Url, username/password. and I also tried using the default provided. both result in the below exception and the Pod keeps crashing.

2022-11-03 15:15:03,286 ERROR [org.apa.cam.kar.ser.ImportService] (executor-thread-0) Error during project import: java.lang.NullPointerException
	at org.apache.camel.karavan.service.GitService.getGitConfig(GitService.java:82)
	at org.apache.camel.karavan.service.GitService.readKameletsFromRepository(GitService.java:121)
	at org.apache.camel.karavan.service.GitService_ClientProxy.readKameletsFromRepository(Unknown Source)
	at org.apache.camel.karavan.service.ImportService.loadCustomKamelets(ImportService.java:86)
	at org.apache.camel.karavan.service.ImportService_ClientProxy.loadCustomKamelets(Unknown Source)
	at org.apache.camel.karavan.service.ImportService_VertxInvoker_loadCustomKamelets_25d455f106e851a1651e88b70b568b08afa572a2.invokeBean(Unknown Source)
	at io.quarkus.vertx.runtime.EventConsumerInvoker.invoke(EventConsumerInvoker.java:41)
	at io.quarkus.vertx.runtime.VertxRecorder$3$1$1.handle(VertxRecorder.java:116)
	at io.quarkus.vertx.runtime.VertxRecorder$3$1$1.handle(VertxRecorder.java:112)
	at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:564)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)

2022-11-03 15:15:03,286 ERROR [org.apa.cam.kar.ser.ImportService] (executor-thread-1) Error during project import: java.lang.NullPointerException
	at org.apache.camel.karavan.service.GitService.getGitConfig(GitService.java:82)
	at org.apache.camel.karavan.service.GitService.readProjectsFromRepository(GitService.java:142)
	at org.apache.camel.karavan.service.GitService_ClientProxy.readProjectsFromRepository(Unknown Source)
	at org.apache.camel.karavan.service.ImportService.importProjects(ImportService.java:54)
	at org.apache.camel.karavan.service.ImportService_ClientProxy.importProjects(Unknown Source)
	at org.apache.camel.karavan.service.ImportService_VertxInvoker_importProjects_de1c71d73fb3f9a09c51bd2fec4f06631c40797f.invokeBean(Unknown Source)
	at io.quarkus.vertx.runtime.EventConsumerInvoker.invoke(EventConsumerInvoker.java:41)
	at io.quarkus.vertx.runtime.VertxRecorder$3$1$1.handle(VertxRecorder.java:116)
	at io.quarkus.vertx.runtime.VertxRecorder$3$1$1.handle(VertxRecorder.java:112)
	at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:564)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)

2022-11-03 15:15:03,388 ERROR [org.apa.cam.kar.ser.KubernetesService] (executor-thread-2) Error starting informers: Operation: [list]  for kind: [Deployment]  with name: [null]  in namespace: [karavan]  failed.
2022-11-03 15:15:03,391 ERROR [io.qua.run.Application] (main) Failed to start application (with profile public): java.lang.NullPointerException
	at org.apache.camel.karavan.service.GitService.getGitConfig(GitService.java:82)
	at org.apache.camel.karavan.service.GitService.onStart(GitService.java:71)
	at org.apache.camel.karavan.service.GitService_Observer_onStart_ed714e8995961c1378e2659056f6eb7c14b6fee8.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:326)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:308)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:76)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:131)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:100)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:110)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:69)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:122)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)

2022-11-03 15:15:03,418 INFO  [org.inf.CLUSTER] (Thread-11) ISPN000080: Disconnecting JGroups channel `ISPN`
2022-11-03 15:15:03,443 INFO  [org.inf.CONTAINER] (Thread-11) ISPN000390: Persisted state, version=13.0.11.Final timestamp=2022-11-03T15:15:03.440861Z

**Comment by mrinalsharma** [comment]
Did you update karavan-secret.xml with correct Git values? What is namespace of your default Kubernetes context? It should be karavan.
Try running `kubectl config set-context --current --namespace=karavan`

**Comment by zetfactor** [comment]
Thanks for the feedback, 

I changed my environment to Minikube, and followed the deployment instructions, and that null issue is now resolved.
