### ISSUE TITLE
How to access Apache karavan UI when using Minikube

### ISSUE THREAD

**Issue by amit88265** [apache/camel-karavan#582]
Hi, 
I am exploring camel-karavan to be used a intgeration tool.  I trying to run camel Karavan on Minikube by following this guide [minikube.md](https://github.com/apache/camel-karavan/blob/main/karavan-cloud/MINIKUBE.md.) After running every command successfully, am not able to access karavan UI to create Routes. The last command. "minikube service karavan --url --namespace karavan"  to access karavan instance not working. Hitting URL from this command does not loading anything from browser. Output from this command is :
http://127.0.0.1:50820
❗  Because you are using a Docker driver on darwin, the terminal needs to be open to run it.

Please help me out. Thanks

**Comment by mrinalsharma** [comment]
I just tried the steps and I am able to see the Karavan Screen. Few things you can try

- Make sure you set the current namespace as karavan ` kubectl config set-context --current --namespace=karavan`
-  Modify minikube/karavan-secret.yaml with the correct git values and registry IP. After making these changes you should run `kubectl apply -f minikube/karavan-secret.yaml -n karavan`
- Make sure that after running command `minikube service karavan --url --namespace karavan` you copy the URL that looks like `http://127.0.0.1:50820/` and paste it into the browser.

**Comment by amit88265** [comment]
Thanks for quick reply.
A few doubts I have:

- What is purpose of Gitea repo? Do I need to install provide that details in secret.
- when to execute this command `kubectl config set-context --current --namespace=karavan`
- There is a field `  image-registry` in secret what is its value? is it minikube ip address or ip adress from command `kubectl -n kube-system get svc registry -o jsonpath='{.spec.clusterIP}'`

**Comment by mrinalsharma** [comment]
you can run `kubectl config set-context --current --namespace=karavan` after creating the namespace.  image-registry value is output of the command `kubectl -n kube-system get svc registry -o jsonpath='{.spec.clusterIP}'`

Karavan keeps the Project in Git repository. you will have to create a git repo and update minikube/karavan-secret.yaml with the Git details.

**Comment by amit88265** [comment]
Created a bitbucket repo and added details in secret.yml. Also followed other steps as you mentioned. But k8s object minikube/karavan.yml is failing with following error.

I am running minikube on Mac M1 (Ventura).

> 

2023-01-03 16:33:33,319 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.quinoa.dev-server.port" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
2023-01-03 16:33:40,037 INFO  [io.qua.sma.ope.run.OpenApiRecorder] (main) CORS filtering is disabled and cross-origin resource sharing is allowed without restriction, which is not recommended in production. Please configure the CORS filter through 'quarkus.http.cors.*' properties. For more information, see Quarkus HTTP CORS documentation
2023-01-03 16:33:40,942 INFO  [io.qua.sch.run.SimpleScheduler] (main) No scheduled business methods found - Simple scheduler will not be started
2023-01-03 16:33:41,242 INFO  [org.apa.cam.kar.ser.KaravanService] (main) Start Karavan
2023-01-03 16:33:41,453 INFO  [org.apa.cam.kar.ser.KaravanService] (main) InfinispanService is starting in local mode
2023-01-03 16:33:43,247 INFO  [org.inf.CONTAINER] (main) ISPN000128: Infinispan version: Infinispan 'Triskaidekaphobia' 13.0.11.Final
2023-01-03 16:33:43,486 INFO  [org.inf.CONTAINER] (main) ISPN000556: Starting user marshaller 'org.infinispan.commons.marshall.ImmutableProtoStreamMarshaller'
2023-01-03 16:33:44,017 INFO  [org.inf.CLUSTER] (main) ISPN000078: Starting JGroups channel `ISPN`
2023-01-03 16:33:44,018 INFO  [org.inf.CLUSTER] (main) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!
2023-01-03 16:33:44,769 ERROR [org.jgr.pro.UDP] (main) failed setting interface to /172.17.0.16: java.net.SocketException: Protocol not available (Error setting socket option)
2023-01-03 16:33:44,772 ERROR [org.jgr.pro.UDP] (main) failed setting interface to /172.17.0.16: java.net.SocketException: Protocol not available (Error setting socket option)
2023-01-03 16:33:44,785 WARN  [org.inf.CONTAINER] (main) ISPN000574: Global state cannot persisted because it is incomplete (usually caused by errors at startup).
2023-01-03 16:33:45,241 ERROR [io.qua.run.Application] (main) Failed to start application (with profile public): java.net.SocketException: Protocol not available
	at java.base/java.net.PlainDatagramSocketImpl.join(Native Method)
	at java.base/java.net.AbstractPlainDatagramSocketImpl.join(AbstractPlainDatagramSocketImpl.java:235)
	at java.base/java.net.MulticastSocket.joinGroup(MulticastSocket.java:328)
	at org.jgroups.protocols.UDP.createSockets(UDP.java:417)
	at org.jgroups.protocols.UDP.start(UDP.java:292)
	at org.jgroups.stack.ProtocolStack.startStack(ProtocolStack.java:881)
	at org.jgroups.JChannel.startStack(JChannel.java:985)
	at org.jgroups.JChannel._preConnect(JChannel.java:849)
	at org.jgroups.JChannel.connect(JChannel.java:358)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:635)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:599)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:577)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl.access$700(BasicComponentRegistryImpl.java:30)
	at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:808)
	at org.infinispan.factories.AbstractComponentRegistry.internalStart(AbstractComponentRegistry.java:354)
	at org.infinispan.factories.AbstractComponentRegistry.start(AbstractComponentRegistry.java:250)
	at org.infinispan.manager.DefaultCacheManager.internalStart(DefaultCacheManager.java:766)
	at org.infinispan.manager.DefaultCacheManager.start(DefaultCacheManager.java:734)
	at org.infinispan.manager.DefaultCacheManager.<init>(DefaultCacheManager.java:302)
	at org.infinispan.manager.DefaultCacheManager.<init>(DefaultCacheManager.java:224)
	at org.apache.camel.karavan.service.InfinispanService.start(InfinispanService.java:81)
	at org.apache.camel.karavan.service.InfinispanService_ClientProxy.start(Unknown Source)
	at org.apache.camel.karavan.service.KaravanService.onStart(KaravanService.java:49)
	at org.apache.camel.karavan.service.KaravanService_Observer_onStart_7085426b23779ed70b18e819ece5dbb680a3147d.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:326)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:308)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:76)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:131)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:100)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:110)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:43)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:123)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
