### ISSUE TITLE
camel karavan Operator 3.18.6 and 3.20.0 are failing !!!! please eitehr rollback to 3.18.5 or fix below asap

### ISSUE THREAD

**Issue by Shahid-Roofi-Khan** [apache/camel-karavan#635]
Note that latest image of camel karavan Operator 3.18.6 and 3.20.0 are failing !!!! please eitehr rollback to 3.18.5 or fix below asap

client.auth-password'
2023-01-26 12:15:08,267 INFO  [org.apa.cam.kar.ser.KaravanService] (main) InfinispanService is starting in local mode
2023-01-26 12:15:08,748 INFO  [org.inf.CONTAINER] (main) ISPN000128: Infinispan version: Infinispan 'Flying Saucer' 14.0.5.Final
2023-01-26 12:15:08,750 INFO  [org.inf.CONTAINER] (main) ISPN000389: Loaded global state, version=14.0.5.Final timestamp=2023-01-26T12:14:48.345496Z
2023-01-26 12:15:08,824 INFO  [org.inf.CONTAINER] (main) ISPN000556: Starting user marshaller 'org.infinispan.commons.marshall.ImmutableProtoStreamMarshaller'
2023-01-26 12:15:09,010 INFO  [org.inf.CLUSTER] (main) ISPN000078: Starting JGroups channel `ISPN`
2023-01-26 12:15:09,010 INFO  [org.inf.CLUSTER] (main) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!
2023-01-26 12:15:09,171 WARN  [org.jgr.pro.UDP] (main) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB
2023-01-26 12:15:09,171 WARN  [org.jgr.pro.UDP] (main) JGRP000015: the receive buffer of socket MulticastSocket was set to 20.00MB, but the OS only allocated 212.99KB
2023-01-26 12:15:09,172 WARN  [org.jgr.pro.UDP] (main) JGRP000015: the send buffer of socket MulticastSocket was set to 1.00MB, but the OS only allocated 212.99KB
2023-01-26 12:15:09,173 WARN  [org.jgr.pro.UDP] (main) JGRP000015: the receive buffer of socket MulticastSocket was set to 25.00MB, but the OS only allocated 212.99KB
2023-01-26 12:15:11,195 INFO  [org.jgr.pro.pbc.GMS] (main) karavan-79d796f467-6dhvr-38742: no members discovered after 2005 ms: creating cluster as coordinator
2023-01-26 12:15:11,205 INFO  [org.inf.CLUSTER] (main) ISPN000094: Received new cluster view for channel ISPN: [karavan-79d796f467-6dhvr-38742|0] (1) [karavan-79d796f467-6dhvr-38742]
2023-01-26 12:15:11,221 INFO  [org.inf.CLUSTER] (main) ISPN000079: Channel `ISPN` local address is `karavan-79d796f467-6dhvr-38742`, physical addresses are `[172.17.0.14:52074]`
2023-01-26 12:15:11,652 INFO  [org.inf.CLUSTER] (main) ISPN000080: Disconnecting JGroups channel `ISPN`
2023-01-26 12:15:11,663 INFO  [org.inf.CONTAINER] (main) ISPN000390: Persisted state, version=14.0.5.Final timestamp=2023-01-26T12:15:11.660652Z
2023-01-26 12:15:11,728 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [public]): java.lang.ClassNotFoundException: com.github.benmanes.caffeine.cache.CacheWriter
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at org.infinispan.factories.DataContainerFactory.construct(DataContainerFactory.java:68)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.doInstantiateWrapper(BasicComponentRegistryImpl.java:189)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.instantiateWrapper(BasicComponentRegistryImpl.java:179)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.getComponent0(BasicComponentRegistryImpl.java:144)
        at org.infinispan.factories.impl.WireContext.get(WireContext.java:20)
        at org.infinispan.interceptors.locking.CorePackageImpl$2.wire(CorePackageImpl.java:62)
        at org.infinispan.interceptors.locking.CorePackageImpl$2.wire(CorePackageImpl.java:58)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeInjection(BasicComponentRegistryImpl.java:337)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeInjection(BasicComponentRegistryImpl.java:345)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeInjection(BasicComponentRegistryImpl.java:345)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.doWireWrapper(BasicComponentRegistryImpl.java:234)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.wireWrapper(BasicComponentRegistryImpl.java:215)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.getComponent0(BasicComponentRegistryImpl.java:150)
        at org.infinispan.factories.impl.WireContext.get(WireContext.java:20)
        at org.infinispan.commands.CorePackageImpl$1.wire(CorePackageImpl.java:29)
        at org.infinispan.commands.CorePackageImpl$1.wire(CorePackageImpl.java:27)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeInjection(BasicComponentRegistryImpl.java:337)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.doWireWrapper(BasicComponentRegistryImpl.java:234)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.wireWrapper(BasicComponentRegistryImpl.java:215)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.getComponent0(BasicComponentRegistryImpl.java:150)
        at org.infinispan.factories.impl.WireContext.get(WireContext.java:20)
        at org.infinispan.cache.impl.CorePackageImpl$9.wire(CorePackageImpl.java:178)
        at org.infinispan.cache.impl.CorePackageImpl$9.wire(CorePackageImpl.java:175)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeInjection(BasicComponentRegistryImpl.java:337)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.wireDependencies(BasicComponentRegistryImpl.java:247)
        at org.infinispan.factories.AbstractComponentRegistry.wireDependencies(AbstractComponentRegistry.java:101)
        at org.infinispan.factories.InternalCacheFactory$AbstractGetAdvancedCache.wireRealCache(InternalCacheFactory.java:218)
        at org.infinispan.factories.CorePackageImpl$2.wire(CorePackageImpl.java:44)
        at org.infinispan.factories.CorePackageImpl$2.wire(CorePackageImpl.java:39)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeInjection(BasicComponentRegistryImpl.java:337)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeInjection(BasicComponentRegistryImpl.java:345)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.wireDependencies(BasicComponentRegistryImpl.java:247)
        at org.infinispan.factories.AbstractComponentRegistry.wireDependencies(AbstractComponentRegistry.java:101)
        at org.infinispan.factories.InternalCacheFactory$AbstractGetAdvancedCache.wireRealCache(InternalCacheFactory.java:218)
        at org.infinispan.factories.CorePackageImpl$2.wire(CorePackageImpl.java:44)
        at org.infinispan.factories.CorePackageImpl$2.wire(CorePackageImpl.java:39)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeInjection(BasicComponentRegistryImpl.java:337)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeInjection(BasicComponentRegistryImpl.java:345)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.wireDependencies(BasicComponentRegistryImpl.java:247)

**Comment by oscerd** [comment]
Hello,
1. Don't use "!" In issues title. We are able to read and the message is enough.
2. In an open source project ASAP doesn't work. Be kind with this community.

Thank you. Have a nice day.

**Comment by mrinalsharma** [comment]
Are you working on wsl?

**Comment by mgubaidullin** [comment]
Should work now in 3.20.0

**Comment by mgubaidullin** [comment]
@Shahid-Roofi-Khan I assume this issue can be closed

**Comment by Shahid-Roofi-Khan** [comment]
had to use custom YAML with startingCSV stick to 3.18.6 to and manual approval of updgrades to make it work. 3.20.0 build fails and web designer does not open. 

We are using minikube latest on windows docker with WSL2 integration (Ubuntu 20.04). Works fine when we rollback.

@mgubaidullin

**Comment by mgubaidullin** [comment]
Deploy Karavan from scratch. Looks like you are reusing previous data in PVC
