### ISSUE TITLE
karavan create projects return HTTP Request to /api/project failed

### ISSUE THREAD

**Issue by zj452008181** [apache/camel-karavan#648]
**version**
karavan v3.20.0
kubernetes v1.23.15

**waht happend**
i create a test spring-boot project in dashboard,the project can successed create but the broswer response '{"details":"Error id 006d68a5-f1d1-4fb4-adf3-ef4424e65192-15","stack":""}',and there has nothing commit to git.deploy this project the pipeline task tips have no pom file.

**pipeline pod logs**
The goal you specified requires a project to execute but there is no POM in this directory (/scripts/test)

**karavan  logs**

2023-02-09 01:18:47,826 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-5528) HTTP Request to /api/project failed, error id: 006d68a5-f1d1-4fb4-adf3-ef4424e65192-15: java.lang.NullPointerException

 	at java.base/java.io.StringReader.<init>(StringReader.java:50)

 	at io.quarkus.qute.Parser$StringReader.<init>(Parser.java:1142)

 	at io.quarkus.qute.EngineImpl.parse(EngineImpl.java:62)

 	at io.quarkus.qute.Engine.parse(Engine.java:36)

 	at io.quarkus.qute.EngineProducer_ProducerMethod_getEngine_c290ac77b5ddc72ba3c5d947ca626000e2af78bc_ClientProxy.parse(Unknown Source)

 	at org.apache.camel.karavan.service.CodeService.getApplicationProperties(CodeService.java:66)

 	at org.apache.camel.karavan.service.CodeService_ClientProxy.getApplicationProperties(Unknown Source)

 	at org.apache.camel.karavan.service.InfinispanService.saveProject(InfinispanService.java:132)

 	at org.apache.camel.karavan.service.InfinispanService_ClientProxy.saveProject(Unknown Source)

 	at org.apache.camel.karavan.api.ProjectResource.save(ProjectResource.java:75)

 	at org.apache.camel.karavan.api.ProjectResource$quarkusrestinvoker$save_ac3a2242a861334c072a996cf0a2a4d0c9eb4761.invoke(Unknown Source)

 	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)

 	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:114)

 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)

 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)

 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)

 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)

 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)

 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)

 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

 	at java.base/java.lang.Thread.run(Thread.java:829)

 

 2023-02-09 01:18:47,826 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (executor-thread-5528) Request failed: java.lang.NullPointerException

 	at java.base/java.io.StringReader.<init>(StringReader.java:50)

 	at io.quarkus.qute.Parser$StringReader.<init>(Parser.java:1142)

 	at io.quarkus.qute.EngineImpl.parse(EngineImpl.java:62)

 	at io.quarkus.qute.Engine.parse(Engine.java:36)

 	at io.quarkus.qute.EngineProducer_ProducerMethod_getEngine_c290ac77b5ddc72ba3c5d947ca626000e2af78bc_ClientProxy.parse(Unknown Source)

 	at org.apache.camel.karavan.service.CodeService.getApplicationProperties(CodeService.java:66)

 	at org.apache.camel.karavan.service.CodeService_ClientProxy.getApplicationProperties(Unknown Source)

 	at org.apache.camel.karavan.service.InfinispanService.saveProject(InfinispanService.java:132)

 	at org.apache.camel.karavan.service.InfinispanService_ClientProxy.saveProject(Unknown Source)

 	at org.apache.camel.karavan.api.ProjectResource.save(ProjectResource.java:75)

 	at org.apache.camel.karavan.api.ProjectResource$quarkusrestinvoker$save_ac3a2242a861334c072a996cf0a2a4d0c9eb4761.invoke(Unknown Source)

 	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)

 	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:114)

 	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)

 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)

 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)

 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)

 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)

 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)

 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)

 	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by mgubaidullin** [comment]
Did you click `Commit` button before `Deploy`?

**Comment by zj452008181** [comment]
yes,Commit add file to  repository,but only push the hello-word.yaml file to repo,did pom.xml shoud i create it?
And what's the solution of karavan create projects return HTTP Request to /api/project failed issue？

![image](https://user-images.githubusercontent.com/26154743/218015219-ab789684-2acd-4319-861f-015e6a53fcf5.png)
![image](https://user-images.githubusercontent.com/26154743/218015353-230ea3ad-1a58-4161-96c5-de7e3677a017.png)

**Comment by mgubaidullin** [comment]
Looks like you use previous version of karavan.
Starting from 3.20.0 karavan creates xxx.camel.yaml

Also when you create project an application.properties file is created

Could you please install karavan 3.20.0 from scratch
