### ISSUE TITLE
Not working in macOS M1

### ISSUE THREAD

**Issue by mahmoodhussam** [apache/camel-karavan#666]
Hi team,

I am trying to build the project on the MacBook M1 2021 but It gave me these errors when I want to run the backend:

Commands: 
`
cd karavan-app
mvn quarkus:dev
`
Errors: 
1) ERROR [org.inf.CONFIG] (Quarkus Main Thread) ISPN000660: DefaultCacheManager start failed, stopping any running components: org.infinispan.commons.CacheConfigurationException: ISPN000085: Error while trying to create a channel using the specified configuration file: default-configs/default-jgroups-udp.xml.

2)  ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile [dev]): java.lang.IllegalArgumentException: failed initializing component ThreadPool in protocol UDP: java.lang.IllegalStateException: failed to create virtual thread pool: java.lang.UnsupportedOperationException: Preview Features not enabled, need to run with --enable-preview

this is all log  
```
mahmoudhussamabbas@JO_G5WCYJNY4N karavan-app % mvn quarkus:dev                                       

[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.apache.camel.karavan:karavan:jar:3.20.1-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-resources-plugin is missing. @ line 208, column 21
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] ------------------< org.apache.camel.karavan:karavan >------------------
[INFO] Building karavan 3.20.1-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- quarkus:2.16.0.Final:dev (default-cli) @ karavan ---
[INFO] Invoking org.apache.maven.plugins:maven-resources-plugin:3.3.0:resources @ karavan
[INFO] Copying 13 resources
[INFO] The encoding used to copy filtered properties files have not been set. This means that the same encoding will be used to copy filtered properties files as when copying other filtered resources. This might not be what you want! Run your build with --debug to see which files might be affected. Read more at https://maven.apache.org/plugins/maven-resources-plugin/examples/filtering-properties-files.html
[INFO] Invoking io.quarkus.platform:quarkus-maven-plugin:2.16.0.Final:generate-code @ karavan
[INFO] Invoking org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile @ karavan
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 40 source files to /Users/mahmoudhussamabbas/Desktop/Projects/camel-karavan-main/karavan-app/target/classes
[INFO] /Users/mahmoudhussamabbas/Desktop/Projects/camel-karavan-main/karavan-app/src/main/java/org/apache/camel/karavan/service/InfinispanService.java: Some input files use or override a deprecated API.
[INFO] /Users/mahmoudhussamabbas/Desktop/Projects/camel-karavan-main/karavan-app/src/main/java/org/apache/camel/karavan/service/InfinispanService.java: Recompile with -Xlint:deprecation for details.
[INFO] /Users/mahmoudhussamabbas/Desktop/Projects/camel-karavan-main/karavan-app/src/main/java/org/apache/camel/karavan/api/KameletResources.java: /Users/mahmoudhussamabbas/Desktop/Projects/camel-karavan-main/karavan-app/src/main/java/org/apache/camel/karavan/api/KameletResources.java uses unchecked or unsafe operations.
[INFO] /Users/mahmoudhussamabbas/Desktop/Projects/camel-karavan-main/karavan-app/src/main/java/org/apache/camel/karavan/api/KameletResources.java: Recompile with -Xlint:unchecked for details.
[INFO] Invoking org.apache.maven.plugins:maven-resources-plugin:3.3.0:testResources @ karavan
[INFO] skip non existing resourceDirectory /Users/mahmoudhussamabbas/Desktop/Projects/camel-karavan-main/karavan-app/src/test/resources
[INFO] Invoking io.quarkus.platform:quarkus-maven-plugin:2.16.0.Final:generate-code-tests @ karavan
[INFO] Invoking org.apache.maven.plugins:maven-compiler-plugin:3.10.1:testCompile @ karavan
[INFO] No sources to compile
Listening for transport dt_socket at address: 5005
2023-02-28 11:37:35,963 WARN  [io.qua.arc.dep.SplitPackageProcessor] (build-82) Detected a split package usage which is considered a bad practice and should be avoided. Following packages were detected in multiple archives: 
- "io.fabric8.tekton.triggers.internal.knative.pkg.apis.duck.v1" found in [io.fabric8:tekton-model-triggers-v1alpha1::jar, io.fabric8:tekton-model-triggers-v1beta1::jar]
- "io.fabric8.tekton.triggers.internal.knative.pkg.apis" found in [io.fabric8:tekton-model-triggers-v1alpha1::jar, io.fabric8:tekton-model-triggers-v1beta1::jar]

2023-02-28 11:37:37,015 WARN  [io.qua.dep.OutputFilter] (Process stdout) Stream is closed, ignoring and trying to continue
2023-02-28 11:37:36,197 WARN  [io.fab.kub.cli.Config] (build-121) Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
2023-02-28 11:37:36,278 INFO  [org.tes.doc.DockerClientProviderStrategy] (build-121) Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
2023-02-28 11:37:36,577 WARN  [org.tes.doc.DockerClientProviderStrategy] (build-121) DOCKER_HOST unix:///var/run/docker.sock is not listening
2023-02-28 11:37:36,581 INFO  [org.tes.doc.DockerMachineClientProviderStrategy] (build-121) docker-machine executable was not found on PATH ([/Users/mahmoudhussamabbas/.jbang/bin, /Users/mahmoudhussamabbas/instantclient, /Users/mahmoudhussamabbas/.nvm/versions/node/v16.14.2/bin, /usr/local/bin, /usr/local/sbin, /usr/local/bin, /usr/bin, /bin, /usr/sbin, /sbin, /Users/mahmoudhussamabbas/.jbang/bin, /Users/mahmoudhussamabbas/instantclient, /Users/mahmoudhussamabbas/.nvm/versions/node/v16.14.2/bin, /usr/local/sbin])
2023-02-28 11:37:36,587 ERROR [org.tes.doc.DockerClientProviderStrategy] (build-121) Could not find a valid Docker environment. Please check configuration. Attempted configurations were:
As no valid configuration was found, execution cannot continue.
See https://www.testcontainers.org/on_failure.html for more details.
2023-02-28 11:37:36,278 INFO  [org.tes.doc.DockerClientProviderStrategy] (build-121) Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
2023-02-28 11:37:36,577 WARN  [org.tes.doc.DockerClientProviderStrategy] (build-121) DOCKER_HOST unix:///var/run/docker.sock is not listening
2023-02-28 11:37:36,581 INFO  [org.tes.doc.DockerMachineClientProviderStrategy] (build-121) docker-machine executable was not found on PATH ([/Users/mahmoudhussamabbas/.jbang/bin, /Users/mahmoudhussamabbas/instantclient, /Users/mahmoudhussamabbas/.nvm/versions/node/v16.14.2/bin, /usr/local/bin, /usr/local/sbin, /usr/local/bin, /usr/bin, /bin, /usr/sbin, /sbin, /Users/mahmoudhussamabbas/.jbang/bin, /Users/mahmoudhussamabbas/instantclient, /Users/mahmoudhussamabbas/.nvm/versions/node/v16.14.2/bin, /usr/local/sbin])
2023-02-28 11:37:36,587 ERROR [org.tes.doc.DockerClientProviderStrategy] (build-121) Could not find a valid Docker environment. Please check configuration. Attempted configurations were:
As no valid configuration was found, execution cannot continue.
See https://www.testcontainers.org/on_failure.html for more details.
2023-02-28 11:37:36,995 WARN  [io.qua.kub.cli.dep.DevServicesKubernetesProcessor] (build-121) Docker isn't working, please configure the Kubernetes client.
[
  [34;1mINFO [m] Checking for existing resources in: /Users/mahmoudhussamabbas/Desktop/Projects/camel-karavan-main/karavan-app/src/main/kue
 r
  netes.


--
2023-02-28 11:37:52,162 INFO  [io.qua.qui.dep.ForwardedDevProcessor] (build-125) Quinoa package manager live coding is up and running on port: 3000 (in 15977ms)
2023-02-28 11:37:52,177 INFO  [io.qua.qui.dep.ForwardedDevProcessor] (build-71) Quinoa is forwarding unhandled requests to port: 3000
2023-02-28 11:37:53,738 WARN  [io.qua.inf.cli.run.InfinispanClientProducer] (Quarkus Main Thread) Use 'quarkus.infinispan-client.username' instead of the deprecated 'quarkus.infinispan-client.auth-username'
2023-02-28 11:37:53,739 WARN  [io.qua.inf.cli.run.InfinispanClientProducer] (Quarkus Main Thread) Use 'quarkus.infinispan-client.password' instead of the deprecated 'quarkus.infinispan-client.auth-password'
2023-02-28 11:37:53,744 INFO  [io.qua.sch.run.SimpleScheduler] (Quarkus Main Thread) No scheduled business methods found - Simple scheduler will not be started
2023-02-28 11:37:53,761 INFO  [org.apa.cam.kar.ser.KaravanService] (Quarkus Main Thread) Start Karavan
2023-02-28 11:37:53,761 WARN  [io.qua.inf.cli.run.InfinispanClientProducer] (Quarkus Main Thread) Use 'quarkus.infinispan-client.username' instead of the deprecated 'quarkus.infinispan-client.auth-username'
2023-02-28 11:37:53,761 WARN  [io.qua.inf.cli.run.InfinispanClientProducer] (Quarkus Main Thread) Use 'quarkus.infinispan-client.password' instead of the deprecated 'quarkus.infinispan-client.auth-password'
2023-02-28 11:37:53,765 INFO  [org.apa.cam.kar.ser.KaravanService] (Quarkus Main Thread) InfinispanService is starting in local mode
2023-02-28 11:37:54,219 INFO  [org.inf.CONTAINER] (Quarkus Main Thread) ISPN000556: Starting user marshaller 'org.infinispan.commons.marshall.ImmutableProtoStreamMarshaller'
2023-02-28 11:37:54,306 INFO  [org.inf.CLUSTER] (Quarkus Main Thread) ISPN000088: Unable to use any JGroups configuration mechanisms provided in properties {}. Using default JGroups configuration!
2023-02-28 11:37:54,386 ERROR [org.inf.CONFIG] (Quarkus Main Thread) ISPN000660: DefaultCacheManager start failed, stopping any running components: org.infinispan.commons.CacheConfigurationException: ISPN000085: Error while trying to create a channel using the specified configuration file: default-configs/default-jgroups-udp.xml
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.buildChannel(JGroupsTransport.java:758)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.initChannel(JGroupsTransport.java:504)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.start(JGroupsTransport.java:485)
        at org.infinispan.remoting.transport.jgroups.CorePackageImpl$1.start(CorePackageImpl.java:42)
        at org.infinispan.remoting.transport.jgroups.CorePackageImpl$1.start(CorePackageImpl.java:27)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:617)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:608)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:577)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:808)
        at org.infinispan.metrics.impl.MetricsCollector.start(MetricsCollector.java:78)
        at org.infinispan.metrics.impl.CorePackageImpl$1.start(CorePackageImpl.java:41)
        at org.infinispan.metrics.impl.CorePackageImpl$1.start(CorePackageImpl.java:34)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:617)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:608)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:577)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:808)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:635)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:599)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:577)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:808)
        at org.infinispan.factories.AbstractComponentRegistry.internalStart(AbstractComponentRegistry.java:357)
        at org.infinispan.factories.AbstractComponentRegistry.start(AbstractComponentRegistry.java:250)
        at org.infinispan.manager.DefaultCacheManager.internalStart(DefaultCacheManager.java:774)
        at org.infinispan.manager.DefaultCacheManager.start(DefaultCacheManager.java:742)
        at org.infinispan.manager.DefaultCacheManager.<init>(DefaultCacheManager.java:303)
        at org.infinispan.manager.DefaultCacheManager.<init>(DefaultCacheManager.java:225)
        at org.apache.camel.karavan.service.InfinispanService.start(InfinispanService.java:81)
        at org.apache.camel.karavan.service.InfinispanService_ClientProxy.start(Unknown Source)
        at org.apache.camel.karavan.service.KaravanService.onStart(KaravanService.java:49)
        at org.apache.camel.karavan.service.KaravanService_Observer_onStart_7085426b23779ed70b18e819ece5dbb680a3147d.notify(Unknown Source)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:328)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:310)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:78)
        at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:131)
        at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:100)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:108)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:104)
        at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.IllegalArgumentException: failed initializing component ThreadPool in protocol UDP: java.lang.IllegalStateException: failed to create virtual thread pool: java.lang.UnsupportedOperationException: Preview Features not enabled, need to run with --enable-preview
        at org.jgroups.stack.ProtocolStack.lambda$initComponents$7(ProtocolStack.java:861)
        at org.jgroups.util.Util.forAllComponents(Util.java:3368)
        at org.jgroups.stack.ProtocolStack.initComponents(ProtocolStack.java:839)
        at org.jgroups.stack.ProtocolStack.initProtocolStack(ProtocolStack.java:795)
        at org.jgroups.stack.ProtocolStack.setup(ProtocolStack.java:438)
        at org.jgroups.JChannel.init(JChannel.java:899)
        at org.jgroups.JChannel.<init>(JChannel.java:123)
        at org.jgroups.JChannel.<init>(JChannel.java:113)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.buildChannel(JGroupsTransport.java:756)
        ... 47 more


2023-02-28 11:37:54,390 WARN  [org.inf.CONTAINER] (Quarkus Main Thread) ISPN000574: Global state cannot persisted because it is incomplete (usually caused by errors at startup).
2023-02-28 11:37:54,431 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile [dev]): java.lang.IllegalArgumentException: failed initializing component ThreadPool in protocol UDP: java.lang.IllegalStateException: failed to create virtual thread pool: java.lang.UnsupportedOperationException: Preview Features not enabled, need to run with --enable-preview
        at org.jgroups.stack.ProtocolStack.lambda$initComponents$7(ProtocolStack.java:861)
        at org.jgroups.util.Util.forAllComponents(Util.java:3368)
        at org.jgroups.stack.ProtocolStack.initComponents(ProtocolStack.java:839)
        at org.jgroups.stack.ProtocolStack.initProtocolStack(ProtocolStack.java:795)
        at org.jgroups.stack.ProtocolStack.setup(ProtocolStack.java:438)
        at org.jgroups.JChannel.init(JChannel.java:899)
        at org.jgroups.JChannel.<init>(JChannel.java:123)
        at org.jgroups.JChannel.<init>(JChannel.java:113)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.buildChannel(JGroupsTransport.java:756)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.initChannel(JGroupsTransport.java:504)
        at org.infinispan.remoting.transport.jgroups.JGroupsTransport.start(JGroupsTransport.java:485)
        at org.infinispan.remoting.transport.jgroups.CorePackageImpl$1.start(CorePackageImpl.java:42)
        at org.infinispan.remoting.transport.jgroups.CorePackageImpl$1.start(CorePackageImpl.java:27)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:617)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:608)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:577)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:808)
        at org.infinispan.metrics.impl.MetricsCollector.start(MetricsCollector.java:78)
        at org.infinispan.metrics.impl.CorePackageImpl$1.start(CorePackageImpl.java:41)
        at org.infinispan.metrics.impl.CorePackageImpl$1.start(CorePackageImpl.java:34)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.invokeStart(BasicComponentRegistryImpl.java:617)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:608)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:577)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:808)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.startDependencies(BasicComponentRegistryImpl.java:635)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.doStartWrapper(BasicComponentRegistryImpl.java:599)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl.startWrapper(BasicComponentRegistryImpl.java:577)
        at org.infinispan.factories.impl.BasicComponentRegistryImpl$ComponentWrapper.running(BasicComponentRegistryImpl.java:808)
        at org.infinispan.factories.AbstractComponentRegistry.internalStart(AbstractComponentRegistry.java:357)
        at org.infinispan.factories.AbstractComponentRegistry.start(AbstractComponentRegistry.java:250)
        at org.infinispan.manager.DefaultCacheManager.internalStart(DefaultCacheManager.java:774)
        at org.infinispan.manager.DefaultCacheManager.start(DefaultCacheManager.java:742)
        at org.infinispan.manager.DefaultCacheManager.<init>(DefaultCacheManager.java:303)
        at org.infinispan.manager.DefaultCacheManager.<init>(DefaultCacheManager.java:225)
        at org.apache.camel.karavan.service.InfinispanService.start(InfinispanService.java:81)
        at org.apache.camel.karavan.service.InfinispanService_ClientProxy.start(Unknown Source)
        at org.apache.camel.karavan.service.KaravanService.onStart(KaravanService.java:49)
        at org.apache.camel.karavan.service.KaravanService_Observer_onStart_7085426b23779ed70b18e819ece5dbb680a3147d.notify(Unknown Source)
        at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:328)
        at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:310)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:78)
        at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:131)
        at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:100)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:108)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:104)
        at java.base/java.lang.Thread.run(Thread.java:1589)


2023-02-28 11:37:54,432 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure

--
```

Device info: 
<img width="629" alt="image" src="https://user-images.githubusercontent.com/39731573/221798976-336213ac-197a-4c79-a341-d8cd739d2e45.png">

**Comment by mahmoodhussam** [comment]
Additional information: 
<img width="1236" alt="Screen Shot 2023-02-28 at 11 49 54 AM" src="https://user-images.githubusercontent.com/39731573/221801526-1ec5fd16-e74e-44c0-994b-9da031275506.png">

**Comment by mahmoodhussam** [comment]
Any Updates?

**Comment by mahmoodhussam** [comment]
Is Camel Karavan work on MacBook M1? @mgubaidullin

**Comment by mgubaidullin** [comment]
I can not test on M1 because I don't have one 😉
However I don't think that the problem is the processor. Karavan app is a normal Java app.
Could you try to reproduce the build process from github action app.yaml

**Comment by mrinalsharma** [comment]
It seems the problem is during the start of the embedded Infinispan. Can you try connecting to remote infinispan.

**Comment by davsclaus** [comment]
what java version do you use

**Comment by mahmoodhussam** [comment]
Solved: 
The problem was related to the java version.

Maven by default used 19.0. 
I download the 11.0.18 Java Version and I changed the maven java default to 11.0.18 using this command.

export JAVA_HOME=`/usr/libexec/java_home -v 11.0.18`

**Comment by davsclaus** [comment]
Thanks for sharing the solution
