### ISSUE TITLE
KubernetesClient not able to access cluster

### ISSUE THREAD

**Issue by mrinalsharma** [apache/camel-karavan#701]
```
aused by: java.net.UnknownHostException: kubernetes.default.svc
        at java.base/java.net.InetAddress$CachedAddresses.get(InetAddress.java:801)
        at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1524)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1381)
        at java.base/java.net.InetAddress.getAllByName(InetAddress.java:1305)
        at okhttp3.Dns.lambda$static$0(Dns.java:39)
        at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:171)
        at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:135)
        at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:187)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
        at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
```
The error is because of line `System.setProperty("kubeconfig", "/Users/mgubaidu/projects/oss/camel-karavan/karavan-app/karavan-kubeconfig.yaml");`

I think it should be changed to 
```System.setProperty("KUBECONFIG", "~/.kube/config");```

After changing to `KUBECONFIG`, code works.

**Comment by davsclaus** [comment]
Thanks, can you maybe send the code change as a PR
