### ISSUE TITLE
Karavan Cloud - Cannot deploy project

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#771]
```
karavan-5c7b9cfb6b-qznf6 karavan 2023-05-17 18:37:11,033 ERROR [org.jbo.thr.errors] (executor-thread-20) Thread Thread[executor-thread-20,5,main] threw an uncaught exception: java.lang.IllegalArgumentException: Name must be provided.
karavan-5c7b9cfb6b-qznf6 karavan 	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.withName(BaseOperation.java:224)
karavan-5c7b9cfb6b-qznf6 karavan 	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.withName(BaseOperation.java:93)
karavan-5c7b9cfb6b-qznf6 karavan 	at org.apache.camel.karavan.service.KubernetesService.getPipelineRunLogWatch(KubernetesService.java:206)
karavan-5c7b9cfb6b-qznf6 karavan 	at org.apache.camel.karavan.service.KubernetesService_ClientProxy.getPipelineRunLogWatch(Unknown Source)
karavan-5c7b9cfb6b-qznf6 karavan 	at org.apache.camel.karavan.api.LogWatchResource.lambda$eventSourcing$0(LogWatchResource.java:69)
karavan-5c7b9cfb6b-qznf6 karavan 	at io.smallrye.context.impl.wrappers.SlowContextualRunnable.run(SlowContextualRunnable.java:19)
karavan-5c7b9cfb6b-qznf6 karavan 	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
karavan-5c7b9cfb6b-qznf6 karavan 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
karavan-5c7b9cfb6b-qznf6 karavan 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
karavan-5c7b9cfb6b-qznf6 karavan 	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
karavan-5c7b9cfb6b-qznf6 karavan 	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
karavan-5c7b9cfb6b-qznf6 karavan 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
karavan-5c7b9cfb6b-qznf6 karavan 	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by davsclaus** [comment]
Okay it smells like its something with tekton pipelines. I found this error about PVC

```
{"severity":"info","timestamp":"2023-05-17T18:43:00.161Z","logger":"tekton-pipelines-controller.event-broadcaster","caller":"record/event.go:285","message":"Event(v1.ObjectReference{Kind:\"PipelineRun\", Namespace:\"karavan\", Name:\"karavan-myproject-jf7mt\", UID:\"496fa9bb-a467-4842-b201-348f9c7181f7\", APIVersion:\"tekton.dev/v1beta1\", ResourceVersion:\"5902\", FieldPath:\"\"}): type: 'Normal' reason: 'Started' ","commit":"8e8c163"}
{"severity":"info","timestamp":"2023-05-17T18:43:00.178Z","logger":"tekton-pipelines-controller","caller":"pipelinerun/affinity_assistant.go:69","message":"Created StatefulSet affinity-assistant-b96b9c4cbd in namespace karavan","commit":"8e8c163","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.Reconciler","knative.dev/kind":"tekton.dev.PipelineRun","knative.dev/traceid":"34442bc3-0de1-4e06-a0c8-5becaaaa316d","knative.dev/key":"karavan/karavan-myproject-jf7mt"}
{"severity":"info","timestamp":"2023-05-17T18:43:00.187Z","logger":"tekton-pipelines-controller","caller":"pipelinerun/affinity_assistant.go:69","message":"Created StatefulSet affinity-assistant-02f000f722 in namespace karavan","commit":"8e8c163","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.Reconciler","knative.dev/kind":"tekton.dev.PipelineRun","knative.dev/traceid":"34442bc3-0de1-4e06-a0c8-5becaaaa316d","knative.dev/key":"karavan/karavan-myproject-jf7mt"}
{"severity":"info","timestamp":"2023-05-17T18:43:00.190Z","logger":"tekton-pipelines-controller","caller":"pipelinerun/pipelinerun.go:878","message":"Creating a new TaskRun object karavan-myproject-jf7mt-karavan-task-dev-quarkus for pipeline task karavan-task-dev-quarkus","commit":"8e8c163","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.Reconciler","knative.dev/kind":"tekton.dev.PipelineRun","knative.dev/traceid":"34442bc3-0de1-4e06-a0c8-5becaaaa316d","knative.dev/key":"karavan/karavan-myproject-jf7mt"}
{"severity":"info","timestamp":"2023-05-17T18:43:00.213Z","logger":"tekton-pipelines-controller","caller":"pipelinerun/pipelinerun.go:697","message":"PipelineRun karavan-myproject-jf7mt status is being set to &{Succeeded Unknown  {2023-05-17 18:43:00.212877792 +0000 UTC m=+2378.081672994} Running Tasks Completed: 0 (Failed: 0, Cancelled 0), Incomplete: 1, Skipped: 0}","commit":"8e8c163","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.Reconciler","knative.dev/kind":"tekton.dev.PipelineRun","knative.dev/traceid":"34442bc3-0de1-4e06-a0c8-5becaaaa316d","knative.dev/key":"karavan/karavan-myproject-jf7mt"}
{"severity":"info","timestamp":"2023-05-17T18:43:00.215Z","logger":"tekton-pipelines-controller.event-broadcaster","caller":"record/event.go:285","message":"Event(v1.ObjectReference{Kind:\"PipelineRun\", Namespace:\"karavan\", Name:\"karavan-myproject-jf7mt\", UID:\"496fa9bb-a467-4842-b201-348f9c7181f7\", APIVersion:\"tekton.dev/v1beta1\", ResourceVersion:\"5902\", FieldPath:\"\"}): type: 'Normal' reason: 'Running' Tasks Completed: 0 (Failed: 0, Cancelled 0), Incomplete: 1, Skipped: 0","commit":"8e8c163"}
{"severity":"info","timestamp":"2023-05-17T18:43:00.215Z","logger":"tekton-pipelines-controller.event-broadcaster","caller":"record/event.go:285","message":"Event(v1.ObjectReference{Kind:\"TaskRun\", Namespace:\"karavan\", Name:\"karavan-myproject-jf7mt-karavan-task-dev-quarkus\", UID:\"8617f5ff-1727-4eb9-b4be-0cc165f67889\", APIVersion:\"tekton.dev/v1beta1\", ResourceVersion:\"5910\", FieldPath:\"\"}): type: 'Normal' reason: 'Started' ","commit":"8e8c163"}
{"severity":"error","timestamp":"2023-05-17T18:43:00.264Z","logger":"tekton-pipelines-controller","caller":"taskrun/taskrun.go:406","message":"TaskRun \"karavan-myproject-jf7mt-karavan-task-dev-quarkus\" workspaces incompatible with Affinity Assistant: more than one PersistentVolumeClaim is bound","commit":"8e8c163","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.taskrun.Reconciler","knative.dev/kind":"tekton.dev.TaskRun","knative.dev/traceid":"cf5945ea-5735-4fe6-bb71-eb7b05de1e6d","knative.dev/key":"karavan/karavan-myproject-jf7mt-karavan-task-dev-quarkus","stacktrace":"github.com/tektoncd/pipeline/pkg/reconciler/taskrun.(*Reconciler).prepare\n\tgithub.com/tektoncd/pipeline/pkg/reconciler/taskrun/taskrun.go:406\ngithub.com/tektoncd/pipeline/pkg/reconciler/taskrun.(*Reconciler).ReconcileKind\n\tgithub.com/tektoncd/pipeline/pkg/reconciler/taskrun/taskrun.go:176\ngithub.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1beta1/taskrun.(*reconcilerImpl).Reconcile\n\tgithub.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1beta1/taskrun/reconciler.go:236\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20230221145627-8efb3485adcf/controller/controller.go:542\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20230221145627-8efb3485adcf/controller/controller.go:491"}
{"severity":"error","timestamp":"2023-05-17T18:43:00.265Z","logger":"tekton-pipelines-controller","caller":"taskrun/taskrun.go:178","message":"TaskRun prepare error: more than one PersistentVolumeClaim is bound","commit":"8e8c163","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.taskrun.Reconciler","knative.dev/kind":"tekton.dev.TaskRun","knative.dev/traceid":"cf5945ea-5735-4fe6-bb71-eb7b05de1e6d","knative.dev/key":"karavan/karavan-myproject-jf7mt-karavan-task-dev-quarkus","stacktrace":"github.com/tektoncd/pipeline/pkg/reconciler/taskrun.(*Reconciler).ReconcileKind\n\tgithub.com/tektoncd/pipeline/pkg/reconciler/taskrun/taskrun.go:178\ngithub.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1beta1/taskrun.(*reconcilerImpl).Reconcile\n\tgithub.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1beta1/taskrun/reconciler.go:236\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20230221145627-8efb3485adcf/controller/controller.go:542\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20230221145627-8efb3485adcf/controller/controller.go:491"}
{"severity":"info","timestamp":"2023-05-17T18:43:00.267Z","logger":"tekton-pipelines-controller.event-broadcaster","caller":"record/event.go:285","message":"Event(v1.ObjectReference{Kind:\"TaskRun\", Namespace:\"karavan\", Name:\"karavan-myproject-jf7mt-karavan-task-dev-quarkus\", UID:\"8617f5ff-1727-4eb9-b4be-0cc165f67889\", APIVersion:\"tekton.dev/v1beta1\", ResourceVersion:\"5910\", FieldPath:\"\"}): type: 'Warning' reason: 'Failed' more than one PersistentVolumeClaim is bound","commit":"8e8c163"}
{"severity":"info","timestamp":"2023-05-17T18:43:00.300Z","logger":"tekton-pipelines-controller","caller":"pipelinerun/pipelinerun.go:697","message":"PipelineRun karavan-myproject-jf7mt status is being set to &{Succeeded Unknown  {2023-05-17 18:43:00 +0000 UTC} Running Tasks Completed: 0 (Failed: 0, Cancelled 0), Incomplete: 1, Skipped: 0}","commit":"8e8c163","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.Reconciler","knative.dev/kind":"tekton.dev.PipelineRun","knative.dev/traceid":"83b05258-42de-44a5-b29e-5cbb468b7f83","knative.dev/key":"karavan/karavan-myproject-jf7mt"}
{"severity":"error","timestamp":"2023-05-17T18:43:00.304Z","logger":"tekton-pipelines-controller","caller":"taskrun/reconciler.go:295","message":"Returned an error","commit":"8e8c163","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.taskrun.Reconciler","knative.dev/kind":"tekton.dev.TaskRun","knative.dev/traceid":"cf5945ea-5735-4fe6-bb71-eb7b05de1e6d","knative.dev/key":"karavan/karavan-myproject-jf7mt-karavan-task-dev-quarkus","targetMethod":"ReconcileKind","error":"1 error occurred:\n\t* more than one PersistentVolumeClaim is bound\n\n","stacktrace":"github.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1beta1/taskrun.(*reconcilerImpl).Reconcile\n\tgithub.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1beta1/taskrun/reconciler.go:295\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20230221145627-8efb3485adcf/controller/controller.go:542\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20230221145627-8efb3485adcf/controller/controller.go:491"}
{"severity":"error","timestamp":"2023-05-17T18:43:00.304Z","logger":"tekton-pipelines-controller","caller":"controller/controller.go:566","message":"Reconcile error","commit":"8e8c163","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.taskrun.Reconciler","knative.dev/kind":"tekton.dev.TaskRun","knative.dev/traceid":"cf5945ea-5735-4fe6-bb71-eb7b05de1e6d","knative.dev/key":"karavan/karavan-myproject-jf7mt-karavan-task-dev-quarkus","duration":0.089733042,"error":"1 error occurred:\n\t* more than one PersistentVolumeClaim is bound\n\n","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\tknative.dev/pkg@v0.0.0-20230221145627-8efb3485adcf/controller/controller.go:566\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20230221145627-8efb3485adcf/controller/controller.go:543\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20230221145627-8efb3485adcf/controller/controller.go:491"}
{"severity":"info","timestamp":"2023-05-17T18:43:00.304Z","logger":"tekton-pipelines-controller.event-broadcaster","caller":"record/event.go:285","message":"Event(v1.ObjectReference{Kind:\"TaskRun\", Namespace:\"karavan\", Name:\"karavan-myproject-jf7mt-karavan-task-dev-quarkus\", UID:\"8617f5ff-1727-4eb9-b4be-0cc165f67889\", APIVersion:\"tekton.dev/v1beta1\", ResourceVersion:\"5910\", FieldPath:\"\"}): type: 'Warning' reason: 'InternalError' 1 error occurred:\n\t* more than one PersistentVolumeClaim is bound\n\n","commit":"8e8c163"}
{"severity":"info","timestamp":"2023-05-17T18:43:00.304Z","logger":"tekton-pipelines-controller","caller":"taskrun/taskrun.go:140","message":"taskrun done : karavan-myproject-jf7mt-karavan-task-dev-quarkus \n","commit":"8e8c163","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.taskrun.Reconciler","knative.dev/kind":"tekton.dev.TaskRun","knative.dev/traceid":"bea1f94c-7b91-4257-b0e1-53a056c2e76b","knative.dev/key":"karavan/karavan-myproject-jf7mt-karavan-task-dev-quarkus"}
{"severity":"info","timestamp":"2023-05-17T18:43:00.306Z","logger":"tekton-pipelines-controller","caller":"controller/controller.go:550","message":"Reconcile succeeded","commit":"8e8c163","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.taskrun.Reconciler","knative.dev/kind":"tekton.dev.TaskRun","knative.dev/traceid":"bea1f94c-7b91-4257-b0e1-53a056c2e76b","knative.dev/key":"karavan/karavan-myproject-jf7mt-karavan-task-dev-quarkus","duration":0.002046708}
{"severity":"info","timestamp":"2023-05-17T18:43:00.310Z","logger":"tekton-pipelines-controller","caller":"resources/pipelinerunstate.go:412","message":"All TaskRuns have finished for PipelineRun karavan-myproject-jf7mt so it has finished","commit":"8e8c163","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.Reconciler","knative.dev/kind":"tekton.dev.PipelineRun","knative.dev/traceid":"c328145d-dd56-4f2a-89d4-a79b2b2f0c0c","knative.dev/key":"karavan/karavan-myproject-jf7mt"}
{"severity":"info","timestamp":"2023-05-17T18:43:00.310Z","logger":"tekton-pipelines-controller","caller":"pipelinerun/pipelinerun.go:697","message":"PipelineRun karavan-myproject-jf7mt status is being set to &{Succeeded False  {2023-05-17 18:43:00.310225626 +0000 UTC m=+2378.179020786} Failed Tasks Completed: 1 (Failed: 1, Cancelled 0), Skipped: 0}","commit":"8e8c163","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.Reconciler","knative.dev/kind":"tekton.dev.PipelineRun","knative.dev/traceid":"c328145d-dd56-4f2a-89d4-a79b2b2f0c0c","knative.dev/key":"karavan/karavan-myproject-jf7mt"}
{"severity":"info","timestamp":"2023-05-17T18:43:00.310Z","logger":"tekton-pipelines-controller.event-broadcaster","caller":"record/event.go:285","message":"Event(v1.ObjectReference{Kind:\"PipelineRun\", Namespace:\"karavan\", Name:\"karavan-myproject-jf7mt\", UID:\"496fa9bb-a467-4842-b201-348f9c7181f7\", APIVersion:\"tekton.dev/v1beta1\", ResourceVersion:\"5926\", FieldPath:\"\"}): type: 'Warning' reason: 'Failed' Tasks Completed: 1 (Failed: 1, Cancelled 0), Skipped: 0","commit":"8e8c163"}
{"severity":"info","timestamp":"2023-05-17T18:43:00.351Z","logger":"tekton-pipelines-controller","caller":"resources/pipelinerunstate.go:412","message":"All TaskRuns have finished for PipelineRun karavan-myproject-jf7mt so it has finished","commit":"8e8c163","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.Reconciler","knative.dev/kind":"tekton.dev.PipelineRun","knative.dev/traceid":"6fe54652-68ca-42de-ade6-13f6ad21961c","knative.dev/key":"karavan/karavan-myproject-jf7mt"}
{"severity":"info","timestamp":"2023-05-17T18:43:00.351Z","logger":"tekton-pipelines-controller","caller":"pipelinerun/pipelinerun.go:697","message":"PipelineRun karavan-myproject-jf7mt status is being set to &{Succeeded False  {2023-05-17 18:43:00.351731792 +0000 UTC m=+2378.220526953} Failed Tasks Completed: 1 (Failed: 1, Cancelled 0), Skipped: 0}","commit":"8e8c163","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.Reconciler","knative.dev/kind":"tekton.dev.PipelineRun","knative.dev/traceid":"6fe54652-68ca-42de-ade6-13f6ad21961c","knative.dev/key":"karavan/karavan-myproject-jf7mt"}
{"severity":"info","timestamp":"2023-05-17T18:43:00.353Z","logger":"tekton-pipelines-controller.event-broadcaster","caller":"record/event.go:285","message":"Event(v1.ObjectReference{Kind:\"PipelineRun\", Namespace:\"karavan\", Name:\"karavan-myproject-jf7mt\", UID:\"496fa9bb-a467-4842-b201-348f9c7181f7\", APIVersion:\"tekton.dev/v1beta1\", ResourceVersion:\"5926\", FieldPath:\"\"}): type: 'Warning' reason: 'Failed' Tasks Completed: 1 (Failed: 1, Cancelled 0), Skipped: 0","commit":"8e8c163"}
{"severity":"info","timestamp":"2023-05-17T18:43:00.385Z","logger":"tekton-pipelines-controller","caller":"controller/controller.go:550","message":"Reconcile succeeded","commit":"8e8c163","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.Reconciler","knative.dev/kind":"tekton.dev.PipelineRun","knative.dev/traceid":"a0f2c94b-290e-4f9d-b696-caac4365ae00","knative.dev/key":"karavan/karavan-myproject-jf7mt","duration":0.006385292}
```

**Comment by davsclaus** [comment]
Argh how are these json logs awful to read in terminals

**Comment by davsclaus** [comment]
```
 k get pvc                                                                                                               ⎈ minikube/karavan
NAME                  STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
karavan-data          Bound    pvc-29777765-f7d3-45af-aa5e-b6d05cce9df3   10Gi       RWO            standard       43m
karavan-jbang-cache   Bound    pvc-ae81eacd-f1e3-4555-a7d0-08701e22a2eb   2Gi        RWO            standard       43m
karavan-m2-cache      Bound    pvc-25d06520-92ed-4c27-9cdb-d245f71d83f3   10Gi       RWO            standard       43m
myproject-runner      Bound    pvc-86f3a465-a67f-41a8-9c0c-5094c7bad7e3   2Gi        RWO            standard       39m
```

**Comment by davsclaus** [comment]
okay so it smells like some tekton setting
https://stackoverflow.com/questions/70089769/tekton-task-fails-with-more-than-one-persistentvolumeclaim-is-bound

```
kubectl edit configmap feature-flags -n tekton-pipelines
```

And setting that anfinity to true, then tekton could start building

However its slow
```
karavan-myproject-8kmrz-karavan-task-dev-quarkus-pod step-karavan-build-deploy /tekton/scripts/script-0-9n74f: line 15: cd: /scripts/myproject: No such file or directory
karavan-myproject-8kmrz-karavan-task-dev-quarkus-pod step-karavan-build-deploy jbang -Dcamel.jbang.version=3.20.4 camel@apache/camel export --local-kamelet-dir=/scripts/kamelets
```

3 minutes so far

**Comment by davsclaus** [comment]
Okay it may be that it cannot checkout from github
```
karavan-myproject-8kmrz-karavan-task-dev-quarkus-pod step-karavan-build-deploy Cloning into '/scripts'...
karavan-myproject-8kmrz-karavan-task-dev-quarkus-pod step-karavan-build-deploy fatal: unable to access 'https://github.com/davsclaus/dummy2.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
karavan-myproject-8kmrz-karavan-task-dev-quarkus-pod step-karavan-build-deploy /tekton/scripts/script-0-9n74f: line 15: cd: /scripts/myproject: No such file or directory
karavan-myproject-8kmrz-karavan-task-dev-quarkus-pod step-karavan-build-deploy jbang -Dcamel.jbang.version=3.20.4 camel@apache/camel export --local-kamelet-dir=/scripts/kamelets
```

**Comment by davsclaus** [comment]
Yeah the scripts folder is empty
```
root@karavan-myproject-8kmrz-karavan-task-dev-quarkus-pod:/scripts# ls -al
total 8
drwxr-xr-x 2 root root 4096 May 17 19:09 .
drwxr-xr-x 1 root root 4096 May 17 19:09 ..
```

**Comment by mgubaidullin** [comment]
@davsclaus could you please git it one more try
