### ISSUE TITLE
docker run for exported dockerfile of quarkus natvie meets error: Resource not found: classpath:/kamelets/timer-source.kamelet.yaml  

### ISSUE THREAD

**Issue by Sabrina-Davis** [apache/camel-karavan#907]
I was testing the basic demo in using the Karavan plugin of VS Code. I created an application for runtime quarkus and deployment for kubernetes. The integration I created described as below:

```yaml
- route:
    id: route-7283
    from:
      uri: kamelet:timer-source/
      id: from-fab0
      parameters:
        message: 11111111111
      steps:
        - log:
            message: ${body}
            id: log-96f0
```

When I click the Jbang run button It works fine.

```bash
jbang -Dcamel.jbang.version=4.0.0 camel@apache/camel run * 
➜  karavan jbang -Dcamel.jbang.version=4.0.0 camel@apache/camel run * 
2023-09-27 10:08:27.017  INFO 38380 --- [           main] org.apache.camel.main.MainSupport   : Apache Camel (JBang) 4.0.0 is starting
2023-09-27 10:08:28.017  INFO 38380 --- [           main] org.apache.camel.main.MainSupport   : Using Java 21 with PID 38380. Started by syrius in /Users/xxx/Downloads/karavan
2023-09-27 10:08:30.680  INFO 38380 --- [           main] .download.MavenDependencyDownloader : Resolved: org.apache.camel:camel-microprofile-health:4.0.0 (took: 2s593ms)
2023-09-27 10:08:32.308  INFO 38380 --- [           main] g.apache.camel.main.BaseMainSupport : Auto-configuration summary
2023-09-27 10:08:32.309  INFO 38380 --- [           main] g.apache.camel.main.BaseMainSupport :     [application.properties]       camel.health.enabled=true
2023-09-27 10:08:32.309  INFO 38380 --- [           main] g.apache.camel.main.BaseMainSupport :     [application.properties]       camel.health.exposureLevel=full
2023-09-27 10:08:32.786  INFO 38380 --- [           main] mel.cli.connector.LocalCliConnector : Camel CLI enabled (local)
2023-09-27 10:08:37.404  INFO 38380 --- [           main] .download.MavenDependencyDownloader : Resolved: org.apache.camel:camel-core:4.0.0 (took: 2s669ms)
2023-09-27 10:08:37.488  INFO 38380 --- [           main] el.impl.engine.AbstractCamelContext : Apache Camel 4.0.0 (test) is starting
2023-09-27 10:08:38.114  INFO 38380 --- [           main] g.apache.camel.main.BaseMainSupport : Property-placeholders summary
2023-09-27 10:08:38.115  INFO 38380 --- [           main] g.apache.camel.main.BaseMainSupport :     [timer-source.kamelet.yaml]    message=11111111111
2023-09-27 10:08:38.355  INFO 38380 --- [           main] el.impl.engine.AbstractCamelContext : Routes startup (started:2)
2023-09-27 10:08:38.357  INFO 38380 --- [           main] el.impl.engine.AbstractCamelContext :     Started route-7283 (kamelet://timer-source)
2023-09-27 10:08:38.358  INFO 38380 --- [           main] el.impl.engine.AbstractCamelContext :     Started timer-source-1 (timer://tick)
2023-09-27 10:08:38.359  INFO 38380 --- [           main] el.impl.engine.AbstractCamelContext : Apache Camel 4.0.0 (test) started in 869ms (build:0ms init:0ms start:869ms)
2023-09-27 10:08:39.159  INFO 38380 --- [ - timer://tick] test.camel.yaml:9                   : 11111111111
2023-09-27 10:08:40.118  INFO 38380 --- [ - timer://tick] test.camel.yaml:9                   : 11111111111
2023-09-27 10:08:41.120  INFO 38380 --- [ - timer://tick] test.camel.yaml:9                   : 11111111111
2023-09-27 10:08:42.125  INFO 38380 --- [ - timer://tick] test.camel.yaml:9                   : 11111111111
2023-09-27 10:08:43.123  INFO 38380 --- [ - timer://tick] test.camel.yaml:9                   : 11111111111
2023-09-27 10:08:44.132  INFO 38380 --- [ - timer://tick] test.camel.yaml:9                   : 11111111111
2023-09-27 10:08:45.127  INFO 38380 --- [ - timer://tick] test.camel.yaml:9                   : 11111111111
2023-09-27 10:08:46.128  INFO 38380 --- [ - timer://tick] test.camel.yaml:9                   : 11111111111
2023-09-27 10:08:47.127  INFO 38380 --- [ - timer://tick] test.camel.yaml:9                   : 11111111111
2023-09-27 10:08:48.131  INFO 38380 --- [ - timer://tick] test.camel.yaml:9                   : 11111111111
2023-09-27 10:08:49.129  INFO 38380 --- [ - timer://tick] test.camel.yaml:9                   : 11111111111
```

I exported the project after and I go to the .export folder trying to follow the instructions in the Dockerfile.native.

```bash
./mvnw package -Pnative -Dquarkus.native.container-build=true

docker build -f src/main/docker/Dockerfile.native -t quarkus/code-with-quarkus .

docker run -i --rm -p 8080:8080 quarkus/code-with-quarkus
```

I meet the error when I was executing the command “docker run -i --rm -p 8080:8080 quarkus/code-with-quarkus”

```bash
docker run -i --rm -p 8084:8080 quarkus/code-with-quarkus
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2023-09-27 02:13:32,274 INFO  [org.apa.cam.qua.cor.CamelBootstrapRecorder] (main) Bootstrap runtime: org.apache.camel.quarkus.main.CamelMainRuntime
2023-09-27 02:13:32,293 INFO  [org.apa.cam.mai.MainSupport] (main) Apache Camel (Main) 4.0.0-RC1 is starting
2023-09-27 02:13:32,317 INFO  [org.apa.cam.mai.BaseMainSupport] (main) Auto-configuration summary
2023-09-27 02:13:32,317 INFO  [org.apa.cam.mai.BaseMainSupport] (main)     [MicroProfilePropertiesSource] camel.main.routesIncludePattern=camel/test.camel.yaml
2023-09-27 02:13:32,317 INFO  [org.apa.cam.mai.BaseMainSupport] (main)     [MicroProfilePropertiesSource] camel.main.sourceLocationEnabled=true
2023-09-27 02:13:32,318 INFO  [org.apa.cam.mai.BaseMainSupport] (main)     [MicroProfilePropertiesSource] camel.health.exposureLevel=full
2023-09-27 02:13:32,318 INFO  [org.apa.cam.mai.BaseMainSupport] (main)     [MicroProfilePropertiesSource] camel.health.enabled=true
2023-09-27 02:13:32,326 WARN  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Lifecycle strategy org.apache.camel.component.kamelet.KameletComponent$LifecycleHandler@14de31d1 vetoed initializing CamelContext (camel-1) due to: Failure creating route from template: timer-source
2023-09-27 02:13:32,326 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) CamelContext (camel-1) vetoed to not initialize due to: Failure creating route from template: timer-source
2023-09-27 02:13:32,326 ERROR [org.apa.cam.qua.mai.CamelMainRuntime] (main) Failed to start application: org.apache.camel.RuntimeCamelException: org.apache.camel.VetoCamelContextStartException: Failure creating route from template: timer-source
	at org.apache.camel.support.service.BaseService.doFail(BaseService.java:413)
	at org.apache.camel.impl.engine.AbstractCamelContext.doFail(AbstractCamelContext.java:2996)
	at org.apache.camel.support.service.BaseService.fail(BaseService.java:342)
	at org.apache.camel.impl.engine.AbstractCamelContext.failOnStartup(AbstractCamelContext.java:3949)
	at org.apache.camel.impl.engine.AbstractCamelContext.init(AbstractCamelContext.java:2075)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:111)
	at org.apache.camel.impl.engine.AbstractCamelContext.start(AbstractCamelContext.java:2081)
	at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:313)
	at org.apache.camel.quarkus.main.CamelMain.doStart(CamelMain.java:94)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:119)
	at org.apache.camel.quarkus.main.CamelMain.startEngine(CamelMain.java:140)
	at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:49)
	at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:45)
	at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot173480958.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot173480958.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: org.apache.camel.VetoCamelContextStartException: Failure creating route from template: timer-source
	at org.apache.camel.component.kamelet.KameletComponent$LifecycleHandler.onContextInitialized(KameletComponent.java:433)
	at org.apache.camel.impl.engine.AbstractCamelContext.doInit(AbstractCamelContext.java:2406)
	at org.apache.camel.quarkus.core.FastCamelContext.doInit(FastCamelContext.java:170)
	at org.apache.camel.support.service.BaseService.init(BaseService.java:83)
	at org.apache.camel.impl.engine.AbstractCamelContext.init(AbstractCamelContext.java:2062)
	... 17 more
Caused by: java.io.FileNotFoundException: Resource not found: classpath:/kamelets/timer-source.kamelet.yaml
	at org.apache.camel.dsl.yaml.YamlRoutesBuilderLoaderSupport.doLoadRouteBuilder(YamlRoutesBuilderLoaderSupport.java:63)
	at org.apache.camel.dsl.support.RouteBuilderLoaderSupport.loadRoutesBuilder(RouteBuilderLoaderSupport.java:101)
	at org.apache.camel.impl.engine.DefaultRoutesLoader.findRoutesBuilders(DefaultRoutesLoader.java:133)
	at org.apache.camel.impl.engine.DefaultRoutesLoader.findRoutesBuilders(DefaultRoutesLoader.java:88)
	at org.apache.camel.spi.RoutesLoader.findRoutesBuilders(RoutesLoader.java:123)
	at org.apache.camel.spi.RoutesLoader.loadRoutes(RoutesLoader.java:75)
	at org.apache.camel.support.RouteTemplateHelper.loadRouteTemplateFromLocation(RouteTemplateHelper.java:106)
	at org.apache.camel.component.kamelet.KameletComponent$LifecycleHandler.createRouteForEndpoint(KameletComponent.java:403)
	at org.apache.camel.component.kamelet.KameletComponent$LifecycleHandler.onContextInitialized(KameletComponent.java:430)
	... 21 more

2023-09-27 02:13:32,341 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [prod]): java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: org.apache.camel.RuntimeCamelException: org.apache.camel.VetoCamelContextStartException: Failure creating route from template: timer-source
	at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:47)
	at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot173480958.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.CamelBootstrapProcessor$boot173480958.deploy(Unknown Source)
	... 7 more
Caused by: java.lang.RuntimeException: org.apache.camel.RuntimeCamelException: org.apache.camel.VetoCamelContextStartException: Failure creating route from template: timer-source
	at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:65)
	at org.apache.camel.quarkus.core.CamelBootstrapRecorder.start(CamelBootstrapRecorder.java:45)
	... 9 more
Caused by: org.apache.camel.RuntimeCamelException: org.apache.camel.VetoCamelContextStartException: Failure creating route from template: timer-source
	at org.apache.camel.support.service.BaseService.doFail(BaseService.java:413)
	at org.apache.camel.impl.engine.AbstractCamelContext.doFail(AbstractCamelContext.java:2996)
	at org.apache.camel.support.service.BaseService.fail(BaseService.java:342)
	at org.apache.camel.impl.engine.AbstractCamelContext.failOnStartup(AbstractCamelContext.java:3949)
	at org.apache.camel.impl.engine.AbstractCamelContext.init(AbstractCamelContext.java:2075)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:111)
	at org.apache.camel.impl.engine.AbstractCamelContext.start(AbstractCamelContext.java:2081)
	at org.apache.camel.impl.DefaultCamelContext.start(DefaultCamelContext.java:313)
	at org.apache.camel.quarkus.main.CamelMain.doStart(CamelMain.java:94)
	at org.apache.camel.support.service.BaseService.start(BaseService.java:119)
	at org.apache.camel.quarkus.main.CamelMain.startEngine(CamelMain.java:140)
	at org.apache.camel.quarkus.main.CamelMainRuntime.start(CamelMainRuntime.java:49)
	... 10 more
Caused by: org.apache.camel.VetoCamelContextStartException: Failure creating route from template: timer-source
	at org.apache.camel.component.kamelet.KameletComponent$LifecycleHandler.onContextInitialized(KameletComponent.java:433)
	at org.apache.camel.impl.engine.AbstractCamelContext.doInit(AbstractCamelContext.java:2406)
	at org.apache.camel.quarkus.core.FastCamelContext.doInit(FastCamelContext.java:170)
	at org.apache.camel.support.service.BaseService.init(BaseService.java:83)
	at org.apache.camel.impl.engine.AbstractCamelContext.init(AbstractCamelContext.java:2062)
	... 17 more
Caused by: java.io.FileNotFoundException: Resource not found: classpath:/kamelets/timer-source.kamelet.yaml
	at org.apache.camel.dsl.yaml.YamlRoutesBuilderLoaderSupport.doLoadRouteBuilder(YamlRoutesBuilderLoaderSupport.java:63)
	at org.apache.camel.dsl.support.RouteBuilderLoaderSupport.loadRoutesBuilder(RouteBuilderLoaderSupport.java:101)
	at org.apache.camel.impl.engine.DefaultRoutesLoader.findRoutesBuilders(DefaultRoutesLoader.java:133)
	at org.apache.camel.impl.engine.DefaultRoutesLoader.findRoutesBuilders(DefaultRoutesLoader.java:88)
	at org.apache.camel.spi.RoutesLoader.findRoutesBuilders(RoutesLoader.java:123)
	at org.apache.camel.spi.RoutesLoader.loadRoutes(RoutesLoader.java:75)
	at org.apache.camel.support.RouteTemplateHelper.loadRouteTemplateFromLocation(RouteTemplateHelper.java:106)
	at org.apache.camel.component.kamelet.KameletComponent$LifecycleHandler.createRouteForEndpoint(KameletComponent.java:403)
	at org.apache.camel.component.kamelet.KameletComponent$LifecycleHandler.onContextInitialized(KameletComponent.java:430)
	... 21 more
```

Is there anything I can do about it? Thanks.

**Comment by mgubaidullin** [comment]
The Karavan's way to build and deploy integration microservices is the following:

<img width="434" alt="Screenshot 2023-09-26 at 10 30 13 PM" src="https://github.com/apache/camel-karavan/assets/1379213/af7dd3aa-3ffa-47be-bb61-40c73f94d6b7">

BTW. Native build is Quarkus specific feature and not supported by Karavan

**Comment by davsclaus** [comment]
Can you post the application.properties, as I think quarkus native requires some special settings for it to work with loading kamelets resources.

**Comment by Sabrina-Davis** [comment]
> Can you post the application.properties, as I think quarkus native requires some special settings for it to work with loading kamelets resources.

Hi @davsclaus I just use the default generated application.properties as below. Is there any clue about it? Much thanks.


```shell
camel.health.enabled=true
camel.health.exposure-level=full
camel.karavan.project-id=karavan
camel.karavan.project-name=karavan
camel.karavan.project-description=karavan
camel.karavan.target=kubernetes
quarkus.container-image.build=true
quarkus.container-image.group=default
quarkus.container-image.name=karavan
quarkus.container-image.builder=jib
quarkus.jib.base-jvm-image=registry.access.redhat.com/ubi8/openjdk-17-runtime:1.16
quarkus.container-image.insecure=true
quarkus.container-image.tag=${DATE}
quarkus.kubernetes.deploy=true
quarkus.kubernetes-client.trust-certs=true
quarkus.kubernetes.image-pull-policy=if-not-present
quarkus.kubernetes.labels."app.kubernetes.io/runtime"=camel
quarkus.kubernetes.add-version-to-label-selectors=false
quarkus.kubernetes.deployment-target=kubernetes
quarkus.kubernetes.replicas=1
camel.main.source-location-enabled=true
quarkus.native.resources.includes=camel/test.camel.yaml
camel.main.routes-include-pattern=camel/test.camel.yaml
```

**Comment by Sabrina-Davis** [comment]
I put the timer-source.kamelet.yaml from https://github.com/apache/camel-kamelets/blob/main/kamelets/timer-source.kamelet.yaml to resources/kamelets/timer-source.kamelet.yaml and add the item to the application.properties.

```shell
quarkus.native.resources.includes=camel/test.camel.yaml,kamelets/timer-source.kamelet.yaml
``` 
and it seems to work. @davsclaus @mgubaidullin
